### ISSUE TITLE
Unable to create an expire at TTL index

### ISSUE THREAD

**Issue by minyoung** [go-mgo/mgo#103]
Trying to create an index with `ExpireAfter: 0` results in the `expireAfterSeconds` option not being applied.

Relevant documentation: http://docs.mongodb.org/manual/tutorial/expire-data/#expire-documents-at-a-specific-clock-time

My guess is that the `omitempty` bson tag option is preventing the `0` value from being sent to mongo when creating the index. There doesn't seem to be an easy way of supporting this without changing the struct/API in some way?

**Comment by niemeyer** [comment]
Have you considered using 1 instead of 0?

**Comment by minyoung** [comment]
How did I miss the obvious?
Yes, that would be acceptable, thanks!

**Comment by tmc** [comment]
@niemeyer would you be open to to something like EnsureTTLIndex that does not omit if ExpiresAfter is zero?

**Comment by niemeyer** [comment]
@tmc Feels somewhat over-engineered.. what's the reasoning?

**Comment by tmc** [comment]
@niemeyer we're operating in a mixed environment and would like the go client library to be able to express the same semantics as other language libraries. The alternative involves either modifying lots of existing collections or using RunCommand -- both non-ideal.

**Comment by niemeyer** [comment]
Setting ExpireAfter at all times is unlike what any other driver does, which means the suggested solution doesn't solve the problem that justifies it.

**Comment by tmc** [comment]
@niemeyer I must be misunderstanding something -- how else would you suggest allowing expireAfterSeconds to be set to zero in a backwards compatible way?

**Comment by niemeyer** [comment]
I haven't suggested setting it to zero. My suggestion is to keep the current mechanism, which is very straightforward, and I'm inviting recommendations for why this is unreasonable and suggested solutions.

I understand this is not what the other drivers do, but each language has different idiosyncrasies we have to live with. In Go, it's extremely common and conventional for zero values to mean nothing, so that's how the struct behaves.

**Comment by tmc** [comment]
@niemeyer in my (now closed) PR I proposed a new method (EnsureTTLIndex) that includes the expireAfterSeconds field even if zero. I didn't read your response here as a rejection of that (it seemed like you thought I was proposing a change in behavior). I'll move along with constructing bson myself.

**Comment by niemeyer** [comment]
I've responded to that branch here:

> Setting ExpireAfter at all times is unlike what any other driver does, which means the suggested solution doesn't solve the problem that justifies it.

In other words, having a whole method dedicated to inserting indexes that _always have the field set no matter what_ does not match any other driver, which was your justification for having this, and it is also an unusual and unexpected concept. We cannot have a method for every field we want to set, let alone a method for each one of the permutations of potential fields that are set.

**Comment by tmc** [comment]
http://godoc.org/github.com/tmc/mgohacks#EnsureTTLIndex in case others need this behavior

**Comment by niemeyer** [comment]
Thanks Travis. There's likely a different way we can do this that might be integrated as well. Will put some further thinking on this.

**Comment by ergoz** [comment]
@niemeyer when you will include in main repo fix by @tmc ? I think it could be great. Because it is big problem now, and dificult to find fix. I spent a lot of time to find it.
Sorry for bad english :)

**Comment by leesper** [comment]
@niemeyer I set it to 1 or 1 * time.Nanosecond or 1 * time.Nanosecond or time.Nanosecond, but it doesn't work, I just can't set TTL to expired at a specified clock time, how can I accomplish this by using mgo? would you plz give an example?!

**Comment by billinghamj** [comment]
This seems like very poor reasoning. Imo, it'd be better to make it a pointer such that it can be set either as the zero-value, or as nil.

An alternative could be to allow -1 to mean zero. Not a good solution, but I don't think it's acceptable to make this impossible with this library.
