### ISSUE TITLE
documentation should mention default consistency and safe modes

### ISSUE THREAD

**Issue by rogpeppe** [go-mgo/mgo#104]
It appears that the documentation does
not mention what default values are used when SetSafe and SetMode
are not called. If I've missed this, the docs should be changed
so a search for "default" will find it (I did not read through the
entire doc in detail). If I haven't missed it, then the docs should
specify the default or say explicitly that the default is undefined.

**Comment by ccressent** [comment]
I couldn't find this either in the documentation, so I resorted to checking the source code:

The call chain is as follow: Dial() -> DialWithTimeout -> DialWithInfo()
At the end of DialWithInfo() the Mode is set to "Strong" ; see https://github.com/go-mgo/mgo/blob/v2/session.go#L427

In DialWithInfo() there is a call to newSession() which in turn calls SetSafe(&Safe{}), and according to he documentation that means "will make the session check for errors, without imposing further constraints"; see https://github.com/go-mgo/mgo/blob/v2/session.go#L1663

I agree with you, it's far from explicit!
I guess one of us should make the corresponding documentation changes and issue a pull request.

**Comment by sha1sum** [comment]
This has been resolved in #273 as well as listing a default value for the `SetSocketTimeout` function documentation, which also was not stated.
