### ISSUE TITLE
Auto parse _id to struct.Id

### ISSUE THREAD

**Issue by guileen** [go-mgo/mgo#107]
Please add it, or be an optional feature.

**Comment by niemeyer** [comment]
Hi there,

I'm sorry, but that's unfortunately not a feature we'll likely have in the near term. Right now there's nothing special about the _id field, and it's not clear why it should be. If we parse both "id" and "_id" to the same field, that's a bug. So it would be incompatible, and it would also break expectations of how the system works. The way to change the default behavior is indeed to use a tag, and if you use mgo often (or any other Go marshaling package, for that matter), you'll find yourself using field tags quite often to tweak the default behavior, and that's just one more of those cases.

**Comment by guileen** [comment]
Maybe map Id to _id is not a good default behavior, but there are some reasonable feature request.

We knows   `foo` field map to `Foo`,  but we don't know what `_foo` will map to.

1. There should be an default map rule for `_` started field.

Since _id is an default field for mongodb, and golang hide non-capital field, these two special design meet together, so we have to add field tag.

I think tag is a good to handle special case, but it's a bad to use tag as default case.

When I using protobuf and mongo together, protobuf is for application protocol, protobuf generate structs, I can't modify the struct tag. Or I should define another struct only for mongodb.

2. map _id to Id could be an option to mgo.Collection, and bson can handle this option by arguments not field tag.
