### ISSUE TITLE
Why it's not possible to name an index?

### ISSUE THREAD

**Issue by dcu** [go-mgo/mgo#111]
I need an index with several keys for optimization purposes and it's causing an error when creating the index.

According to the documentation ( http://docs.mongodb.org/manual/reference/limits/#Index-Name-Length ):

    Fully qualified index names, which includes the namespace and the dot separators (i.e. <database name>.<collection name>.$<index name>), cannot be longer than 128 characters.

But you can also specify the name of the index: http://docs.mongodb.org/manual/reference/method/db.collection.createIndex/#options-for-all-index-types

    Optional. The name of the index. If unspecified, MongoDB generates an index name by concatenating the names of the indexed fields and the sort order.

**Comment by minyoung** [comment]
Are there any workarounds to not being able to specify the index name?
Is using db.Run our best option?

**Comment by niemeyer** [comment]
The reason it's not provided is because it tends to be both unnecessary and cumbersome to integrate in the API. Please consider for a moment how the methods look like.

What's the real need for naming the index?

**Comment by minyoung** [comment]
The need comes in when the generated name is too long, which can happen if/when you're trying to create an index on multiple long fields (having a long database/collection name doesn't help either since that's included in the namespace entry)

**Comment by dcu** [comment]
Yeah this is really needed. Can we try to find a good solution?

**Comment by niemeyer** [comment]
Sounds good. We'll have soemthing on the next release.

**Comment by minyoung** [comment]
![thank-you-cat-17842704083](https://cloud.githubusercontent.com/assets/126625/9285972/86921e9a-42a0-11e5-8074-a54dd77ba94b.jpeg)
