### ISSUE TITLE
Is `ExpireAfter: 0` supported?

### ISSUE THREAD

**Issue by dcu** [go-mgo/mgo#112]
According to the documentation you can set it to 0 and have a field defining the date when the document should be expired: http://docs.mongodb.org/manual/tutorial/expire-data/#expire-documents-at-a-specific-clock-time

    For each document in the collection, set the indexed date field to a value corresponding to the time the document should expire. If the indexed date field contains a date in the past, MongoDB considers the document expired.

The `mgo` documentation doesn't mention this case.

**Comment by niemeyer** [comment]
We don't support that because Go has a special meaning for zero values that we make good use of. If we accepted a zero ExpireAfter field, we'd need a different field to tell that we're actually using an ExpireAfter.

Note you can set the value to 1 and have the same behavior.

**Comment by dcu** [comment]
Are you sure it's the same behavior? If so I think we should at least document it because it's no even in the official doc

**Comment by niemeyer** [comment]
It's documented, and it's even in the section you quoted above: _"If the indexed date field contains a date in the past, MongoDB considers the document expired."_ That's why zero works.. 0, 1, 2.. are all dates in the past.

**Comment by niemeyer** [comment]
Fixed the wording to be slightly more precise. ExpireAfter is actually a delta which is applied on the indexed field. If the indexed date plus the delta field contains a date in the past, MongoDB considers the document expired. Small deltas make the field date expire very close to its defined date, which will make it behave the same in practice.
