### ISSUE TITLE
Change Apply with Sort

### ISSUE THREAD

**Issue by windweller** [go-mgo/mgo#115]
```
	var items []Item
	_, err := coll.Find(bson.M{"ReceiverId": userJson.ObjId}).Sort("-createdTime").Apply(change, &items)
```

I was reading the documentation of `.Apply()` method and it says:

```
The Sort and Select query methods affect the result of Apply.  In case
multiple documents match the query, Sort enables selecting which document to act upon by ordering it first.
```
I'm a bit confused by this sentence. I want to update those records and return records that are sorted. This documentation says `which document to act upon by ordering first`. Will `Apply()` act upon all the records or do I need to take extra steps??

**Comment by niemeyer** [comment]
Per the documentation, the findAndModify command acts on one document only:

> Apply runs the findAndModify MongoDB command, which allows updating, upserting or removing a  document matching a query and atomically returning either the old version (the default) or the new version of the document (when ReturnNew is true). If no objects are found Apply returns ErrNotFound.
