### ISSUE TITLE
Persistent Boolean Value

### ISSUE THREAD

**Issue by heindl** [go-mgo/mgo#118]
Hey. We're having some unexpected behavior while unmarshalling boolean struct properties. It seems like properties without a BSON tag should be ignored. Is there a behind the scenes cache?
    
    package test

    import (
    	. "github.com/smartystreets/goconvey/convey"
    	"testing"
    	"github.com/facebookgo/mgotest"
    	"time"
    	"gopkg.in/mgo.v2/bson"
    )

    type BoolTest struct {
    	A string `bson:"a"`
    	B bool
    }

    func TestBoolRepoIssue(t *testing.T) {

    	Convey("should not persist struct value without a bson tag", t, func() {

    		mg := &mgotest.Server{
    			T:           t,
    			StopTimeout: 15 * time.Second,
    		}
    		mg.Start()

    		coll := mg.Session().DB("meteor").C("testing")
    		b := BoolTest{
    			A: "Testing",
    			B: true,
    		}
    		So(coll.Insert(b), ShouldBeNil)

    		n := BoolTest{}
    		So(coll.Find(bson.M{}).One(&n), ShouldBeNil)
    		So(n.A, ShouldEqual, "Testing")
    		So(n.B, ShouldBeFalse)
    	})

    }

**Comment by niemeyer** [comment]
The bson tag will tweak the marshaling behavior, but the default behavior is to marshal any exported fields. If you don't want to export a particular field, you can tag it with `bson:"-"`, though.

**Comment by niemeyer** [comment]
This behavior is consistent with every other marshaling package for Go, by the way.
