### ISSUE TITLE
bson: Attempted to marshal empty Raw document

### ISSUE THREAD

**Issue by dvyukov** [go-mgo/mgo#120]
The following program fails with the following panic:
```go
package main

import (
	"fmt"
	"github.com/go-mgo/mgo/bson"
)

func main() {
	data := []byte("\xcf\x00\x00\x00\x100\x000000\x010\x00000000" +
		"00\b00\x000\x04x\x006\x00\x00\x00\x1000\x0000" +
		"00\x0200\x00\x01\x00\x00\x00\x00\n00000000" +
		"000000000000\x00\x01\x0000000" +
		"000\x00\n000000000000000" +
		"00000000000000000000" +
		"00000000\x00\x1000\x000000\x0200" +
		"\x00\x01\x00\x00\x00\x00\n00\x00\x0300\x00\x18\x00\x00\x00\x100" +
		"\x000000\x020\x00\x01\x00\x00\x00\x00\b0\x000\x00\x100" +
		"\x000000\n0\x00\x100\x000000\x110\x0000" +
		"000000\x00")
	var v S
	if err := bson.Unmarshal(data, &v); err != nil {
		panic(err)
	}
	_, err := bson.Marshal(&v)
	if err != nil {
		fmt.Printf("%#v\n", v)
		panic(err)
	}
}

type S struct {
	X bson.RawD `bson:",omitempty"`
}
```
```
main.S{X:bson.RawD{bson.RawDocElem{Name:"", Value:bson.Raw{Kind:0x0, Data:[]uint8(nil)}}}}
panic: Attempted to marshal empty Raw document
```

I don't know whether there is something to fix or not, but this does not allow to marshal something that was successfully unmarshalled.

on commit 7d0c3292d228c50afd01306aa6f20e37539b09d5

**Comment by dvyukov** [comment]
@niemeyer So it is not Raw, it is RawD that contains an empty Raw. But the empty Raw was created by Unmarshal.

The question is: if empty Raw's are invalid, should not Unmarshal have failed rather than create an empty Raw?

**Comment by niemeyer** [comment]
There's indeed a bug here. The random data is attempting to unmarshal a BSON array into a RawD, but the latter is supposed to behave as a BSON document in all circumstances, which means it should ignore the array and have the X element unset. The test case being added makes the problem clear.

Thanks for this report, Dmitry. Great catch.
