### ISSUE TITLE
Next call for tail iterator panics when session is closed 

### ISSUE THREAD

**Issue by mjs** [go-mgo/mgo#121]
[The documentation for Query.Tail()](http://godoc.org/gopkg.in/mgo.v2#Query.Tail) says that if the timeout is "set to -1, Next will not timeout, and will continue waiting for a result for *as long as the cursor is valid and the session is not closed.*". I was hoping to be able to close the session used by a tail iterator from another goroutine (as the highlighted text suggests) as a way to unblock a Next call if the iterator should stop. Unfortunately this doesn't appear to be the case and results in a panic.

The following code illustrates the problem:

```go
package main

import (
	"fmt"
	"os"

	"gopkg.in/mgo.v2"
	"gopkg.in/mgo.v2/bson"
)

func checkErr(label string, err error) {
	if err != nil {
		fmt.Println(label+":", err)
		os.Exit(1)
	}
}

func main() {
	info := &mgo.DialInfo{
		Addrs: []string{"127.0.0.1:50018"},
	}
	session, err := mgo.DialWithInfo(info)
	checkErr("Dial", err)

	coll := session.DB("test").C("something")
	coll.DropCollection()
	err = coll.Create(&mgo.CollectionInfo{
		Capped:   true,
		MaxBytes: 2048,
	})
	checkErr("Create", err)

	err = coll.Insert(bson.M{"_id": "foo"})
	checkErr("Insert", err)

	iter := coll.Find(nil).Tail(-1)
	var doc bson.M
	if !iter.Next(&doc) {
		panic("expected first call to Next to succeed")
	}

	// The session would typically be closed in a another goroutine
	// but doing it in the same goroutine here for simplicity.
	session.Close()

	iter.Next(&doc) // panics
}
```

Note that the panic only seems to occur if the iterator has previously returned a result. 

The panic looks like this:

```
panic: Session already closed

goroutine 16 [running]:
runtime.panic(0x573860, 0xc2080010e0)
	/usr/lib/go/src/pkg/runtime/panic.c:279 +0xf5
gopkg.in/mgo%2ev2.(*Session).cluster(0xc208056000, 0x573860)
	/home/menno/go/src/gopkg.in/mgo.v2/session.go:1282 +0x72
gopkg.in/mgo%2ev2.(*Session).acquireSocket(0xc208056000, 0xc20805a101, 0x0, 0x0, 0x0)
	/home/menno/go/src/gopkg.in/mgo.v2/session.go:3408 +0x286
gopkg.in/mgo%2ev2.(*Iter).acquireSocket(0xc208024000, 0xc2080041d0, 0x0, 0x0)
	/home/menno/go/src/gopkg.in/mgo.v2/session.go:2886 +0x48
gopkg.in/mgo%2ev2.(*Iter).getMore(0xc208024000)
	/home/menno/go/src/gopkg.in/mgo.v2/session.go:2913 +0x32
gopkg.in/mgo%2ev2.(*Iter).Next(0xc208024000, 0x563f00, 0xc208038088, 0xc20805a501)
	/home/menno/go/src/gopkg.in/mgo.v2/session.go:2730 +0x266
main.main()
	/home/menno/go/src/freshfoo.com/mgo-iter-panic/main.go:46 +0x5bc

...
```

Is this expected? Should it be possible to unblock Next by closing the underlying Session? If so, let's fix it. If not, I will submit a documentation patch to make this clearer.

**Comment by niemeyer** [comment]
I apologize for the bug induced as the documentation is incorrect. There's no provision in Next for working with closed sessions, and attempting to manipulate a session while or after a session is closed has always been reporting as a critical error via a panic.

Given the design of the interface, it wouldn't sound too bad to have Iter.Close unblocking iter.Next, though. Are you still looking for a workaround to that problem?

**Comment by mjs** [comment]
This didn't cause an issue with released software or anything like that. It's just a problem I ran in to during development. There was no significant impact beyond my own confusion :)

I worked around this long ago so I'm not looking for anything to change in mgo. Unblocking Next on Iter.Close would be nice though.
