### ISSUE TITLE
EnsureIndex for a wildcard text index causes an error

### ISSUE THREAD

**Issue by ventres** [go-mgo/mgo#125]
The function collection.EnsureIndex (http://godoc.org/labix.org/v2/mgo#Collection.EnsureIndex) fails when you try to create a wildcard text index. For example:
```
index :=  Index{
  Key: []string{"$text:$**"},
  Name: "my_wildcard_index",
}
err := db.C("my_collection").EnsureIndex(index)
if err != nil {
  panic(err)
}
```
This code will panic with the following error:
panic: invalid index key: want "[$<kind>:][-]<field name>", got "$text:$**"

Here is the relevant doc for wildcard text indexes: http://docs.mongodb.org/manual/tutorial/create-text-index-on-multiple-fields/

If you replace the wildcard $** with a field name (e.g. foo), EnsureIndex runs without error.

**Comment by niemeyer** [comment]
This was previously reported in #65 and closed in a581209d. Coming out in the stable release later today.
