### ISSUE TITLE
Document that BSON serialisation is guaranteed to preserve struct order

### ISSUE THREAD

**Issue by abligh** [go-mgo/mgo#132]
I believe serialising a struct to BSON does so in the order that the `struct` fields are defined (or that it isn't). Testing appears to show that it does so today, but there is no documentation that it is *guaranteed* to do so (or that it isn't).

It would be very useful if this was a guaranteed property, for instance so that hashes of BSON values of documents could be compared (see for example: http://stackoverflow.com/questions/31371339/is-mgo-bson-marshalling-guaranteed-to-preserve-order-of-struct-components ). However, if it is not guaranteed, it would also be useful to tell people so they don't rely on it.

`gob` for instance is careful to say at: https://golang.org/pkg/encoding/gob/
> *Structs are sent as a sequence of (field number, field value) pairs ... The field number is defined by the type of the encoded struct: the first field of the encoded type is field 0, the second is field 1, etc. ... [The] fields are always sent in order of increasing field number*

**Comment by niemeyer** [comment]
Thanks for raising this issue, Alex.

You can definitely rely on the ordering being stable and in field order. Even inside mgo itself there is logic that relies on this being the case.

I will amend the documentation as suggested.
