### ISSUE TITLE
read tcp i/o timeout

### ISSUE THREAD

**Issue by zygis** [go-mgo/mgo#140]
I made some function for long running queries:
```
func CopyForLogRun(maxDurationString string) (*mgo.Session, error) {
	duration, err := time.ParseDuration(maxDurationString)
	if err != nil {
		return nil, err
	}
	copySafety := &mgo.Safe{W: 1, WTimeout: int(duration.Seconds() * 1000)}
	copy := session.Copy()
	copy.SetSafe(copySafety)
	copy.SetSocketTimeout(duration)
	copy.SetSyncTimeout(duration)
	return copy, nil
}
```
I tried to set timeout's for "1h" but nothing... I got error after 10-20 secs. Are there any other timeout settings?

**Comment by niemeyer** [comment]
It should definitely not timeout after 10-20 seconds. Can you please provide an example that demonstrates that happening?  It should be one file, and self-contained (should create data, if it needs it, and then run).

**Comment by zygis** [comment]
Well, it's complicated :) Collection size is ~14mln documents, and depends on disk speed and ram size  (my working set hardly fits ram) how quickly mongodb responds.

But one interesting thing: when I wrote wrapper for mgo, we used mongodb 2.6.x and I pretty sure I tested these timeouts before releasing to production. Now our sharded (current collection is not sharded) cluster is upgraded to 3.0.x . Maybe new mongodb version added some "magic" to timeouts or sockets?

And I feel another issue is somehow releated to this:
One process has ~100 goroutines, and each goruotine has a session copy, and some times some goroutines blocks (without any errors), but when I trying to restart whole process I got lot of these:
```
net.(*pollDesc).Wait(0xc208546060, 0x72, 0x0, 0x0) 
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47 
net.(*pollDesc).WaitRead(0xc208546060, 0x0, 0x0) 
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43 
net.(*netFD).Read(0xc208546000, 0xc20906b9e0, 0x24, 0x24, 0x0, 0x7fa6d0167c10, 0xc20bfe4b58) 
        /usr/local/go/src/net/fd_unix.go:242 +0x40f 
net.(*conn).Read(0xc208b02148, 0xc20906b9e0, 0x24, 0x24, 0x0, 0x0, 0x0) 
        /usr/local/go/src/net/net.go:121 +0xdc 
gopkg.in/mgo%2ev2.fill(0x7fa6d0168fa8, 0xc208b02148, 0xc20906b9e0, 0x24, 0x24, 0x0, 0x0) 
        /fake/path/dependencies/src/gopkg.in/mgo.v2/socket.go:504 +0x75 
gopkg.in/mgo%2ev2.(*mongoSocket).readLoop(0xc208e59880) 
        /fake/path/dependencies/src/gopkg.in/mgo.v2/socket.go:521 +0x126 
created by gopkg.in/mgo%2ev2.newSocket 
        /fake/path/dependencies/src/gopkg.in/mgo.v2/socket.go:168 +0x3d3
```

And I'm 90% sure, that these errors started to appear after upgrading to mongodb 3.0.x

**Comment by niemeyer** [comment]
That leads me to believe you have a real timeout, rather than a 10-20 seconds one. This error message comes from the socket itself, and mgo is properly updating the timeout deadlines at appropriate moments, otherwise every application would be broken.

If you can't find any information that negates that, it's hard to provide any help.

**Comment by zygis** [comment]
It's ok. I done some debugging and found that this is my server issue. When I set very short timeout it works as expected. But can't pass 30 sec barrier. On different server long timeout works as expected too.

Sorry for false alarm. Closing issue.

**Comment by justmao945** [comment]
@zygis can you share the server issue with me ? I have this problem, too.
