### ISSUE TITLE
CollectionNames() is broken empty collection for Mongo 3.0

### ISSUE THREAD

**Issue by proteneer** [go-mgo/mgo#144]
mongodb version v3.0.5

Create an empty collection 

```
coll := db.C(id)
err := coll.Create(&mgo.CollectionInfo{})
if err != nil {
	return nil, err
}

results, err := db.CollectionNames()

fmt.Println("COLLECTION NAMES", results, err)
```

CollectionNames shows an empty list.

This bug is only present on mongodb v3.0.5, not v2.6.10

**Comment by proteneer** [comment]
Actually it doesn't even matter if the Collection is empty or not, CollectionNames() is just plain old broken.

**Comment by proteneer** [comment]
```
<database>.system.namespaces
Deprecated since version 3.0: Access this data using listCollections.

The <database>.system.namespaces collection contains information about all of the database’s collections.
```

**Comment by niemeyer** [comment]
Please try updating your driver. Current releases already use the command with newer servers.

**Comment by proteneer** [comment]
fixed, thanks!
