### ISSUE TITLE
Bulk API for Updates

### ISSUE THREAD

**Issue by kunapuli09** [go-mgo/mgo#146]
Hello Contributors,
  Thanks for your great contributions. MongoDB suggests users to use single doc with more updates approach rather than multiple document inserts for performance reasons. But without a Bulk update API it's difficult to complete implementations using mgo api. I am wondering about the status of that Bulk Update feature and also any temporary work arounds. The other question is that we are willing to do this feature and contribute back. But need some direction and guidance from start to finish. 

Regards,
Krishna Kunapuli
VIPER Engineering Team

**Comment by niemeyer** [comment]
Thanks for your interest, Krishna. This feature is long due and should already have landed by now, but it's still pending a few more tests on my side. I will close this issue to notify you when the feature lands in v2-unstable.

**Comment by kunapuli09** [comment]
Thanks for the update, btw, I am using mgo db.Run() api with a command prepared for a batch.  Prepared a bson.M like described in mongodb docs http://blog.mongodb.org/post/84922794768/mongodbs-new-bulk-api

Sample  bson.M
{
        update: 'collection name'
      , updates: [{ 
            q: { a : 1 }
          , u: { $inc : { x : 1}}
          , multi: true/false
          , upsert: true/false
        }, ...]
      , writeConcern: {
        w: 1, j: true, wtimeout: 1000
      }
      , ordered: true/false
    }
