### ISSUE TITLE
Report number of modified documents in ChangeInfo

### ISSUE THREAD

**Issue by zygis** [go-mgo/mgo#149]
Mongo shell
```
var a = db.test.update({a:1},{$addToSet:{b:4}},{multi:true})
print(JSON.stringify(a, "", "  "))

{
  "nInserted": 0,
  "nUpserted": 0,
  "nMatched": 2,
  "nModified": 0,
  "nRemoved": 0
}
```
Mgo
```
c := s.DB("database").C("test")
a, _ := c.UpdateAll(bson.M{"a":1}, bson.M{"$addToSet":bson.M{"b":4}})
log.Printf("%+v", a)
// &{Updated:2 Removed:0 UpsertedId:<nil>}
```
Looks like `ChangeInfo.Updated` == `nMatched`
Is it possible get `nModified` somehow?

**Comment by niemeyer** [comment]
Yes, that's correct. ChangeInfo.Updated is currently the number of matched documents for historical reasons (the other information is not available on old servers). The upcoming stable which should be out today or tomorrow allows you to use the bulk API to obtain the new details, if the server supports them.

I'm also keeping this issue open to introduce support for that in ChangeInfo itself in the future.

**Comment by ivoviz** [comment]
Not sure if I should open a new issue for this, anyways: Is it possible to change the Update API (or create a new one) so we can see whether our update actually affected a document or not? Currently we can only do it with Find and Apply (AFAIK), but it would be really convenient to have the Update method return ChangeInfo as well.
