### ISSUE TITLE
Problem when use on Go 1.5

### ISSUE THREAD

**Issue by prsolucoes** [go-mgo/mgo#155]
panic: no reachable servers

goroutine 1 [running]:
_/Users/paulo/Documents/workspaces/go/overlytics/app.(*Database).NewSession(0xc82006e108, 0x5c30a)
	/Users/paulo/Documents/workspaces/go/overlytics/app/db.go:21 +0x84
_/Users/paulo/Documents/workspaces/go/overlytics/app.(*Database).NewDatabase(0xc82006e108)
	/Users/paulo/Documents/workspaces/go/overlytics/app/db.go:13 +0x21
_/Users/paulo/Documents/workspaces/go/overlytics/web.(*WebServer).CreateDatabase(0xc820126f30)
	/Users/paulo/Documents/workspaces/go/overlytics/web/server.go:29 +0x2a
main.main()
	/Users/paulo/Documents/workspaces/go/overlytics/main.go:10 +0x44

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 19 [sleep]:
time.Sleep(0x1dcd6500)
	/usr/local/go/src/runtime/time.go:59 +0xf9
gopkg.in/mgo%2ev2.(*mongoCluster).syncServersLoop(0xc82019c000)
	/Users/paulo/Developer/go/src/gopkg.in/mgo.v2/cluster.go:384 +0x484
created by gopkg.in/mgo%2ev2.newCluster
	/Users/paulo/Developer/go/src/gopkg.in/mgo.v2/cluster.go:76 +0x1d0

goroutine 35 [sleep]:
time.Sleep(0x12a05f200)
	/usr/local/go/src/runtime/time.go:59 +0xf9
gopkg.in/mgo%2ev2.(*mongoServer).pinger(0xc8200b0fc0, 0x1)
	/Users/paulo/Developer/go/src/gopkg.in/mgo.v2/server.go:297 +0x1b4
created by gopkg.in/mgo%2ev2.newServer
	/Users/paulo/Developer/go/src/gopkg.in/mgo.v2/server.go:90 +0x162

goroutine 38 [sleep]:
time.Sleep(0x12a05f200)
	/usr/local/go/src/runtime/time.go:59 +0xf9
gopkg.in/mgo%2ev2.(*mongoServer).pinger(0xc8200b1180, 0x1)
	/Users/paulo/Developer/go/src/gopkg.in/mgo.v2/server.go:297 +0x1b4
created by gopkg.in/mgo%2ev2.newServer
	/Users/paulo/Developer/go/src/gopkg.in/mgo.v2/server.go:90 +0x162

**Comment by niemeyer** [comment]
Please update the code. This was fixed earlier today (see #153).
