### ISSUE TITLE
Docs don't say if mgo.Session is goroutine-safe

### ISSUE THREAD

**Issue by glasser** [go-mgo/mgo#156]
Can I use a single mgo.Session on multiple goroutines safely (assuming I'm OK with their commands/queries being put in a serial order on the network)?  The docs don't seem to say.  I see `Session.Clone`... do I need to call that and use cloned versions in different goroutines?

**Comment by niemeyer** [comment]
Yes, it's safe. Will keep this issue open to improve docs.
