### ISSUE TITLE
bson.Binary mapping to struct problem

### ISSUE THREAD

**Issue by exu** [go-mgo/mgo#157]
I have problem with decoding binary data on recent Go 1.5
Here is example which result is 

    package main
    
    import (
    	"fmt"
    	"labix.org/v2/mgo"
    	"labix.org/v2/mgo/bson"
    )
    
    type Sample struct {
    	Name string      `bson:"name"`
    	Bin  bson.Binary `bson:"bin"`
    }
    
    func main() {
    	session, err := mgo.Dial("localhost")
    	if err != nil {
    		panic(err)
    	}
    	defer session.Close()
    
    	session.SetMode(mgo.Monotonic, true)
    
    	c := session.DB("test").C("bin")
    	c.DropCollection()
    
    	err = c.Insert(&Sample{Name: "CoreSample1", Bin: bson.Binary{0x00, []byte("Some random goop")}})
    	if err != nil {
    		panic(err)
    	}
    
    	result := Sample{}
    	err = c.Find(bson.M{"name": "CoreSample1"}).One(&result)
    	if err != nil {
    		panic(err)
    	}
    
    	fmt.Println(result)
    }

When I run it I should get bson.Binary with bytes in Data field but get empty byte array

    ❯ go run binary.go
    {CoreSample1 {0 []}}

**Comment by niemeyer** [comment]
Any reason why you're not simply using `Bin []byte` as the field, as would be natural in Go?

**Comment by niemeyer** [comment]
So, there was indeed a bug decoding plain BSON binaries into bson.Binary, and I have fixed it. But there's really no reason to do that. It's much more convenient to simply use the conventional []byte slice straight into your own field.

Please do update your code to use gopkg.in/mgo.v2 instead of labix.org. The latter is very old by now.

**Comment by exu** [comment]
@niemeyer thanks for figuring this out :)
