### ISSUE TITLE
Question - Is there a way to define a Raw dynamic query

### ISSUE THREAD

**Issue by joeybloggs** [go-mgo/mgo#164]
Is it possible to fire a query using a user defined query?

Example
```go

// string the user typed in from http post or command line
var userInputString string

userInputString := "{\"username\":\"joeybloggs\"}"

// db connection stuff

c := sess.DB("").C("users")

var results []*Users

c.Pipe(userInputString).Find(&users).All()

```

I am looking at creating a GUI frontend for working with MongoDB and need to query the DB using user defined queries, but so far it looks like I would have to parse the query myself to create a bson.M or map; I just thought that the bson.M must get broken down to a native MongoDB query at some point and perhaps there is a way to just bypass the bson.M stuff.

I apologize if I have just missed it, but could not find anything in the documentation.

**Comment by niemeyer** [comment]
You can use any sort of map that is proper to the data you're working with, and can also use bson.D if your MongoDB document depends on ordering of keys for some reason (the case with some internal commands). Anything the mgo.v2/bson package can work with can also be used with mgo itself.
