### ISSUE TITLE
How to use single connection

### ISSUE THREAD

**Issue by JesusIslam** [go-mgo/mgo#165]
Hello, is there a way to use single connection (not using pool) with mgo? I need to use this to do transaction for TokuMX.

**Comment by niemeyer** [comment]
Depending on what you mean by that there are different approaches you can take. But I believe what you are asking for is not really what you want. If sounds like what you want is to communicate with a single socket, and for that you can actually use and benefit from the usual connection pool. Just Dial and use the session as usual. Until you Refresh the session, the underlying socket is reserved for that one session and won't change, even if errors happen.

If that's not it, please reopen the issue.
