### ISSUE TITLE
How can to get it in CHINA?

### ISSUE THREAD

**Issue by louis-sherren** [go-mgo/mgo#167]
The `go get gopkg.in/mgo.v2` doesn't work here!

**Comment by niemeyer** [comment]
I'm not entirely sure about what to say.. I'd very much like to have it working for anyone, anywhere, but it's tricky if public services are arbitrarily broken. Any suggestions?

**Comment by louis-sherren** [comment]
Well I have got mgo from a third-party website, not sure if my version is the latest and stable one.
Some hosts in the world are blocked in China because of the **Great Fire Wall**, and I think gopkg.in is in the block list. 
Consider there are tons of developers here, please consider building up a mirror or something so that we can access this easily  : )

**Comment by niemeyer** [comment]
Sorry, but this is really out of my control. I cannot keep replicating the service on alternative locations in pursue of an entry which happens to be out of a block list I have no control or understanding of, and cannot even tell whether a given service is blacklisted or not. I'd encourage someone that is within the firewall to create and maintain such a service instead.

Are you interested in doing that?

**Comment by louis-sherren** [comment]
Hmmm, I'd love to do that but I don't have that much resources and time.
