### ISSUE TITLE
Docs for Query.Hint and Collection.EnsureIndexKey should mention how to specify a descending index

### ISSUE THREAD

**Issue by wojcikstefan** [go-mgo/mgo#169]
Right now, the information about prefixing a field name with "-" is only briefly mentioned in `Query.Sort`. All of these methods' docs should include an example of a descending index IMHO.

**Comment by niemeyer** [comment]
The documentatoin of both Query.Hint and Collection.EnsureIndexKey point to the documentation of EnsureIndex for further details, which contains a complete and thorough description of the index key layout. It doesn't seem reasonable to copy that documentation to every method that depends on it.
