### ISSUE TITLE
Bulk update and bulk upsert features.

### ISSUE THREAD

**Issue by ishail** [go-mgo/mgo#172]
Hi, I see bulk update and bulk upsert in v2-unstable but not in master. I would like to know how much stable this is and whether it is ready to use in production or not.

**Comment by niemeyer** [comment]
I'm working on the last few pieces of the next stable. Should be out today or tomorrow.

**Comment by ishail** [comment]
Hi niemeyer, Did you finish working on that?

**Comment by nidhind** [comment]
thank for doing a great job mgo
