### ISSUE TITLE
Document is corrupted error from bson.Unmarshal, but json.Unmarshal works.

### ISSUE THREAD

**Issue by liweiz** [go-mgo/mgo#175]
Hello,

I'm trying to use the bson.Unmarshal func. However, I have not been able to have it work. I always got the error msg: Document is corrupted. I'm not sure what caused the error since the json.Unmarshal func works just fine. It is probably a newbie question. But could you help me on this?

Thanks in advance,

Liwei

```
package main

import (
	"encoding/json"
	"fmt"

	"gopkg.in/mgo.v2/bson"
)

func main() {
	var b = []byte(`{"Name": null, "Order": "a"}`)
	// Test bson
	var o0 interface{}
	err0 := bson.Unmarshal(b, &o0)
	if err0 != nil {
		fmt.Println("\nbson error: ", err0)
	} else {
		fmt.Printf("\nb by bson: %+v", o0)
	}
	// Test json
	var o1 interface{}
	err1 := json.Unmarshal(b, &o1)
	if err1 != nil {
		fmt.Println("\njson error: ", err1)
	} else {
		fmt.Printf("\nb by json: %+v", o1)
	}
}
```

Output:
bson error:  Document is corrupted
b by json: map[Name:<nil> Order:a]

**Comment by niemeyer** [comment]
The bson format is not json.. very far from it. You'll not be able to (un)marshal one with the other.
