### ISSUE TITLE
Go vet complaints "Id" => "ID" 

### ISSUE THREAD

**Issue by MaerF0x0** [go-mgo/mgo#176]
There are many complaints from `go vet` that  `func somethingId` should be `func somethingID`

Can we create those and just make the originals be wrappers? Backwards compat and dependent libs can still mock/interface w/o `go vet` complaints.  Let me know if you want a PR.

**Comment by niemeyer** [comment]
It's not worth the trouble, for the same reason that the standard library itself contains such historical names.
