### ISSUE TITLE
Error: Failed to start all prcesses when doing "make startdb"

### ISSUE THREAD

**Issue by valnci** [go-mgo/mgo#179]
Hi,

I need to test that the mgo driver is build properly on my machine. I also have the supervisord installed. However, when I execute the "make startdb" command the execution is blocked as shown in the below screenshot:
![mgoerror](https://cloud.githubusercontent.com/assets/14192245/10453789/e842e8e4-71cc-11e5-9633-2fee42c677d6.PNG)

I checked the supervisord.log; there are some status codes which I've come to understand to a very limited extent. 
![mgosupervisordlog](https://cloud.githubusercontent.com/assets/14192245/10453884/b27f4abc-71cd-11e5-97d2-1b902b26a038.PNG)

Can anyone please guide me on this issue (why "Failed to start all processes" ) and also to understand the status codes in the log ?    

System details:
System: RHEL ppc64le
supervisord version: 3.1.3

Please let me know if any other information is required.

Thanks in advance,

Valnci

**Comment by niemeyer** [comment]
As reported, supervisord is indeed failing to start some of the processes. So the first thing to find out is why.. if you get into the supervisord console (supervisorctl), you can run status and tail to get logs for specific processes.

**Comment by niemeyer** [comment]
Please feel free to reopen this ticket if you have more details you'd like to share.
