### ISSUE TITLE
The special character problem

### ISSUE THREAD

**Issue by adililhan** [go-mgo/mgo#181]
Greetings,

i have a special character in my password (%). I see "cannot unescape password in URL" message when i try connect to db.

what will i do?

https://github.com/go-mgo/mgo/blob/v2-unstable/session.go#L490

**Comment by niemeyer** [comment]
Being part of a URL, it needs to conform to URL semantics. The `%` character may be escaped as `%25`, which is the escape character `%` plus the hex encoding of the `%` character code.

One optino to avoid escaping altogether is using [Session.Login](http://gopkg.in/mgo.v2#Session.Login).
