### ISSUE TITLE
`bson.Raw` marshalling is not threadsafe

### ISSUE THREAD

**Issue by rgarcia** [go-mgo/mgo#182]
I'm decoding some bson data in two steps using `bson.Raw`, and my decoders are running in parallel. If I have one decoder, everything works, but if I have more than one, I get `Document is corrupted` errors.

I believe this is because `bson.Raw`'s `Data` is instantiated in the parser by reference: https://github.com/go-mgo/mgo/blob/v2-unstable/bson/decode.go#L286

I would mention this in the docs or potentially change `bson.Raw` decoding to `copy` into a new slice.

**Comment by niemeyer** [comment]
Can you please clarify the scenario further?  How are you using bson.Raw, and what is being done in parallel?

**Comment by rgarcia** [comment]
I'm reading a file generated from `mongodump` and parsing each document into a `struct` containing a `bson.Raw` field. I then pass this struct to a set of goroutines for additional processing, which includes parsing the `bson.Raw` field. This parsing fails if I have more than one goroutine.

**Comment by niemeyer** [comment]
bson.Raw is composed of only a Kind and Data fields, and when the bson package is asked to unmarshal it neither of these fields are touched, so I cannot see how decoding it in parallel would fail.

Can you please provide a reproducer?

**Comment by rgarcia** [comment]
Sorry, this appears to be an issue with using a `bufio.Scanner` on the file produced by `mongodump`. The `Bytes()` method on the scanner returns a slice that is changed on subsequent calls to `Scan()`, so passing that to `bson.Marshal` is not threadsafe.
