### ISSUE TITLE
Program panics when calling Ping() on a broken session.

### ISSUE THREAD

**Issue by RealHacker** [go-mgo/mgo#183]
When I call session.Ping() to check if the session is valid, program panics because of nil pointer dereference. 

To reproduce:
1. Start the program that establish a Mongo session.
2. Now kill the Mongo server.
3. Let the program check the session by calling Ping().
4. Program panics.

**Comment by niemeyer** [comment]
Right, that's expected. The solution is to never call methods on nil sessions. Instead, check the error that was generated on the failed attempt to get that session.

**Comment by RealHacker** [comment]
The session variable itself is not nil, it is some variable reference within the session, the code should check for nil before calling method on it.

Besides, how can I check if the session is valid if Ping() is not usable?

**Comment by niemeyer** [comment]
Please provide more details of the error, such as a small and self-contained reproduced and the real error you get when running it.
