### ISSUE TITLE
Сreate a collection with a specified engine options

### ISSUE THREAD

**Issue by nexcode** [go-mgo/mgo#186]
In MongoDB manual:
db.createCollection(name, {
capped: boolean,
autoIndexId: boolean,
size: number,
max: number,
storageEngine: document })

MGO provides «func (c *Collection) Create(info *CollectionInfo) error» method.

type CollectionInfo struct {
    DisableIdIndex bool
    ForceIdIndex bool
    Capped   bool
    MaxBytes int
    MaxDocs  int
}

How specified storage engine?

**Comment by niemeyer** [comment]
We'll get that fixed in the next stable. Thanks for the report.

**Comment by niemeyer** [comment]
Hmm.. there's a misunderstanding here, though. To change the storage engine, you need to start the MongoDB server itself indicatring which storage engine you want to use. The storageEngine option in the createCollection command allows you to specify _options_ for the previously chosen storage engine. We'll implement support for that, but it's not what the title here describes.
