### ISSUE TITLE
bson.ObjectId type prevents clear separation of DB code from logic

### ISSUE THREAD

**Issue by eaigner** [go-mgo/mgo#190]
I attempted to separate all our data objects from the driver implementation by. Consider following struct

```
type A struct {
  ID bson.ObjectId `bson:"_id"`
  FieldOne string
}
```

If I use this struct in another package (e.g. model layer) the `bson.ObjectId` leaks in there from the package concerning only DB operations. Even if I try to implement the `Getter` and `Setter` methods on my custom type, I have to include the driver `bson` package import my model package.

Would it be possible to provide a method that tells the driver what type to use for specific `bson` package types? (or is there already?)

**Comment by niemeyer** [comment]
I don't see what the issue is there. Nothing in mgo or bson forces you to expose a bson.ObjectId out of your own API. Of course, if you use a type from a third-party package in your own public structs, that type will become visible to clients of your package. The answer if you don't want that to happen is to just not do that. Use that type internally only, and expose only the APIs you wish from your own package.

**Comment by niemeyer** [comment]
By the way, you can also use any other type in an `_id` field (ints, strings, etc), if you'd prefer that.

**Comment by eaigner** [comment]
Ideally I want to define my documents only once. The problem is if in this case struct `A` (my document) crosses the API boundary between let's say the storage package and the business logic package, I expose the `bson.ObjectId` type to the logic. In order to avoid that I'd have to create 2 nearly identical structs that only differ in the type used for the `ID` field.

**Comment by eaigner** [comment]
ad 2) The problem is the documents already exists in the databse with ID being an object ID, so I could not use `string` or any other type than `bson.ObjectId` for the `ID` field.

**Comment by niemeyer** [comment]
Right, if you want to hide the fact the third-party package is being used, you'll need to implement a layer that is responsible for hiding it. And indeed, if there's data already _typed as object ids_ (!) in the database, the proper way to handle those with mgo is by using the _bson.ObjectId type_ (!).

**Comment by niemeyer** [comment]
Ah, and there's one more solution for this as well: implement your own type that internally marshals as an ObjectId via the bson.Getter and Setter interfaces.

**Comment by eaigner** [comment]
The `Getter` and `Setter` is unfortunately also not an option since the interface has a `bson.Raw` in it's signature. So I'd need the bson package import again in my other package that should be driver independent.

I imagine an struct tag keyword could help here

```
type A struct {
  ID string `bson:"_id,oid"`
}
```

to tell the driver that this field is supposed to be an object ID without relying on a special type. Could also be 

    []byte `bson:"_id,oid"`

 or whatever fits best since object IDs are bytes. Or both `string` and `[]byte` and the driver chooses if the hex (`string`) or raw (`[]byte`) representation is required.

**Comment by niemeyer** [comment]
The bson package is cleanly built around the concept of values being values and types being types, and we're of course not being creative here. Obviously the whole language is oriented around that truism. You can pass bson.ObjectId around (and bson.JavaScript, bson.RegEx, etc), have them in maps, interfaces, and so on, and it still works correctly. The moment you break that, awkward things will start happening. For example, `collection.FindId(person.Id)`? Nope, doesn't work.

Sorry, but this is feeling like an unreasonable hack.

**Comment by eaigner** [comment]
Yeah, I see. Thanks for your time!
