### ISSUE TITLE
panic: no reachable servers

### ISSUE THREAD

**Issue by pedrto** [go-mgo/mgo#193]
Trying to run the following code:

    package main
    
    import (
        "github.com/codegangsta/martini"
        "github.com/codegangsta/martini-contrib/binding"
        "github.com/codegangsta/martini-contrib/render"
        "gopkg.in/mgo.v2"
    )
    
    type Wish struct {
        Name        string `form:"name"`
        Description string `form:"description"`
    }
    
    // DB Returns a martini.Handler
    func DB() martini.Handler {
        session, err := mgo.Dial("localhost")
        if err != nil {
            panic(err)
        }
    
        return func(c martini.Context) {
            s := session.Clone()
            c.Map(s.DB("advent"))
            defer s.Close()
            c.Next()
        }
    }
    
    // GetAll returns all Wishes in the database
    func GetAll(db *mgo.Database) []Wish {
        var wishlist []Wish
        db.C("wishes").Find(nil).All(&wishlist)
        return wishlist
    }
    
    func main() {
        m := martini.Classic()
        m.Use(render.Renderer())
        m.Use(DB())
    
        m.Get("/wishes", func(r render.Render, db *mgo.Database) {
            r.HTML(200, "list", GetAll(db))
        })
    
        m.Post("/wishes", binding.Form(Wish{}), func(wish Wish, r render.Render, db *mgo.Database) {
            db.C("wishes").Insert(wish)
            r.HTML(200, "list", GetAll(db))
        })
    
        m.Run()
    }

 gives me:

    panic: no reachable servers
    
    goroutine 1 [running]:
    main.DB(0x0, 0x0)
    	/home/me/work/Xmas/server.go:27 +0x150
    main.main()
    	/home/me/work/Xmas/server.go:48 +0x79
    
    goroutine 17 [syscall, locked to thread]:
    runtime.goexit()
    	/usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1
    
    goroutine 18 [sleep]:
    time.Sleep(0x1dcd6500)
    	/usr/lib/go/src/runtime/time.go:59 +0xf9
    gopkg.in/mgo%2ev2.(*mongoCluster).syncServersLoop(0xc820102000)
    	/home/me/work/src/gopkg.in/mgo.v2/cluster.go:386 +0x484
    created by gopkg.in/mgo%2ev2.newCluster
    	/home/me/work/src/gopkg.in/mgo.v2/cluster.go:78 +0x1d0
    
    goroutine 24 [sleep]:
    time.Sleep(0x37e11d600)
    	/usr/lib/go/src/runtime/time.go:59 +0xf9
    gopkg.in/mgo%2ev2.(*mongoServer).pinger(0xc8201080e0, 0x1)
    	/home/me/work/src/gopkg.in/mgo.v2/server.go:296 +0x1b0
    created by gopkg.in/mgo%2ev2.newServer
    	/home/me/work/src/gopkg.in/mgo.v2/server.go:89 +0x160

I tried changing

    func DB() martini.Handler {
        session, err := mgo.Dial("localhost")
        if err != nil {
            panic(err)
        }

To 

    func DB() martini.Handler {
        session, err := mgo.Dial("127.0.0.1")
        if err != nil {
            panic(err)
        }

As recommended in [this][2] post. Nothing.

Using "DialWithInfo" like in [this][3] case, returns the same error.

**May I have an explanation of what is causing this error?** 

I'm using go 1.5.1 on linux/amd64.

  [2]: https://groups.google.com/forum/#!topic/golang-nuts/wRQwpRJvDHU
  [3]: https://github.com/go-mgo/mgo/issues/43

**Comment by pedrto** [comment]
Reinstalling MongoDB fixed the issue.

**Comment by DishankJindal** [comment]
I have a Digital Ocean Cloud server and installed mongodb successfully. But i am not able to connect the server ip to my program. It panics and says not reachable. But works fine with localhost. Plz explain...
