### ISSUE TITLE
time.Now() and time.Now().UTC() save in mongo as UTC +0000

### ISSUE THREAD

**Issue by nexcode** [go-mgo/mgo#194]
**time.Now()** and **time.Now().UTC()** save in mongo like this:
`"time" : ISODate("2015-11-29T11:13:19.039+0000")`

How to save date in UTC without conversion in UTC+0000?

For example:
`"time" : ISODate("2015-11-29T14:13:19.039+0300")`

**Comment by niemeyer** [comment]
There's no way, unfortunately. Mongo's timestamp format doesn't hold a timestamp, so it will always be stored as UTC. If you want to store a timezone, you'll need to do that out of band.
