### ISSUE TITLE
Question: what could possibly go wrong after i/o timeout

### ISSUE THREAD

**Issue by zygis** [go-mgo/mgo#197]
```
// func from my simple wrapper for mgo
func Copy() *mgo.Session {
	copy := session.Copy()
	copy.SetSafe(sessionSafety) // &mgo.Safe{W: 1, WTimeout: int(defaultDuration.Seconds() * 1000)}
	copy.SetSocketTimeout(defaultDuration) // 1 minute
	if len(tags) > 0 {
		copy.SelectServers(tags)
	}
	return copy
}
```
I have ~10 goroutines. All these goroutines doing few thousands writes per second. If goroutine received error is "i/o timeout", then current goroutine doing something like that:
```
session.Close()
session = wrapper.Copy()
// OR
session = session.New()
```
But after that my program from ~50-120% cpu goes to ~1000% cpu (12 core server), and write speed falling down drastically. Should I after this kind of error do something different instead of Copy? I don't know internals of driver, but maybe something is going wrong when copying session over and over again?

**Comment by niemeyer** [comment]
That doesn't sound quite right. This is a very cheap operation, and the only possible reason of it eating all of your CPU is if it's in a tight loop, which would mean improper use of the functionality. This would also be unrelated to the "i/o timeout" you received, unless the local client code is failing in such a way. In fact, are you sure this is the cause, rather than the consequence?  If your system goes to 1000% CPU, you'll likely observe timeouts as an *effect*.

**Comment by zygis** [comment]
I agree, this doesn't sound quite right. And I am just guessing.
But looks like sequence of the problem is: 
1. i/o timeout
2. increasing cpu usage
3. all writes become at least 30ms slower
I added bunch of timers to my code, and "become at least 30ms slower" part is 
```
err := collection.Update(bson.M, bson.M)
```
i/o timeout of course not happening without any load :) I tried to pause goroutines and resuming after few minutes (to check if these problems related to server load), but write speed and cpu usage stays the same after resume (memory, number of connections to mongo are ok). Only program restart can fix this. After restart everything is going as expected.

When program is restarting sometimes I see these errors:
```
goroutine xxx [IO wait]:
net.runtime_pollWait(0x7fec154aba78, 0x72, 0xc8200780b0)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82013a370, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82013a370, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82013a310, 0xc8202c6510, 0x24, 0x24, 0x0, 0x7fec154a7028, 0xc8200780b0)
        /usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8202ca020, 0xc8202c6510, 0x24, 0x24, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:172 +0xe4
gopkg.in/mgo%2ev2.fill(0x7fec14a660d8, 0xc8202ca020, 0xc8202c6510, 0x24, 0x24, 0x0, 0x0)
        /home/www/program/current/dependencies/src/gopkg.in/mgo.v2/socket.go:533 +0x6c
gopkg.in/mgo%2ev2.(*mongoSocket).readLoop(0xc820336460)
        /home/www/program/current/dependencies/src/gopkg.in/mgo.v2/socket.go:550 +0x132
created by gopkg.in/mgo%2ev2.newSocket
        /home/www/program/current/dependencies/src/gopkg.in/mgo.v2/socket.go:197 +0x402
```
My guess: something bad is going with socket after i/o timeout.

**Comment by niemeyer** [comment]
My guess, again, is that it's happening in the opposite direction:

1. increasing cpu usage
2. all writes become at least 30ms slower
3. i/o timeout

I wouldn't look at the mgo driver as being the culprit there without some further evidence.

**Comment by zygis** [comment]
Maybe you're right. I had to ask before diving deeper to code :)
