### ISSUE TITLE
Collection stats

### ISSUE THREAD

**Issue by Nurza** [go-mgo/mgo#199]
Hello, I want to run the command stats() on a collection like:

db.mycollection.stats()

How can I do this with mgo please?

Thank you!

**Comment by Nurza** [comment]
2 weeks after... Thanks me!

```go
var stats bson.D
session.DB("mydb").Run(bson.D{{"collStats", "mycollection"}}, &stats)
fmt.Println("Stats:", stats)
```

**Comment by niemeyer** [comment]
Glad you managed to find your way through MongoDBs documentation.

For future usage questions, I'd recommend using the mgo-users mailing list. The tracker here is used mainly for bug reporting and work tracking.
