### ISSUE TITLE
How to use poolLimit ?

### ISSUE THREAD

**Issue by figoxu** [go-mgo/mgo#200]
On the document you write on 2013-7-10
https://groups.google.com/forum/#!msg/mgo-users/tDmuztwViDg/iHGnXFbNq78J
![001](https://cloud.githubusercontent.com/assets/10055828/12016214/5ef0337e-ad83-11e5-9f0c-0648737d45f9.png)
the date of poolLImit code pushed is 2014-7-21 .
![002](https://cloud.githubusercontent.com/assets/10055828/12016277/00b91d6a-ad84-11e5-9820-0ba62db4ab08.png)

Dos any improvement during these commit ? How do i cap the connections ?

**Comment by niemeyer** [comment]
Here is a more recent discussion on the same topic:

https://groups.google.com/forum/?fromgroups#!topic/mgo-users/SKXLf21HmEk
