### ISSUE TITLE
Document Validation

### ISSUE THREAD

**Issue by pjebs** [go-mgo/mgo#205]
For Mongo 3.2, they have document validation.

https://docs.mongodb.org/manual/core/document-validation/

https://godoc.org/gopkg.in/mgo.v2#Collection.Create
https://godoc.org/gopkg.in/mgo.v2#CollectionInfo

The CollectionInfo struct can include a bson field called `validator` which can allow users to predefine the server-side validation rules.

That would be a useful feature.

**Comment by niemeyer** [comment]
Indeed, we'll have that in the next stable. Thanks for the report.
