### ISSUE TITLE
Null pointer in bulk.go

### ISSUE THREAD

**Issue by mandeepbrar** [go-mgo/mgo#206]
Shouldnt the following functions in bulk.go have null checks

func (b *Bulk) runUpdate(action *bulkAction, result *BulkResult, berr *bulkError) bool {
	lerr, err := b.c.writeOp(bulkUpdateOp(action.docs), b.ordered)
        if(lerr!= nil) {    /*********This check is not there**********/
	      result.Matched += lerr.N
	      result.Modified += lerr.modified
        }
	return b.checkSuccess(berr, lerr, err)
}

func (b *Bulk) runRemove(action *bulkAction, result *BulkResult, berr *bulkError) bool {
	lerr, err := b.c.writeOp(bulkDeleteOp(action.docs), b.ordered)
        if(lerr!= nil) {     /*********This check is not there**********/
	      result.Matched += lerr.N
 	      result.Modified += lerr.modified
        }
	return b.checkSuccess(berr, lerr, err)
}

**Comment by niemeyer** [comment]
Yes, this has been fixed already. Sorry about that.
