### ISSUE TITLE
Bson encode AddMap can't support map[interface{}]interface{}

### ISSUE THREAD

**Issue by RyouZhang** [go-mgo/mgo#207]
encoder.go line number 130

add check map key type

func (e *encoder) addMap(v reflect.Value) {
	for _, k := range v.MapKeys() {
		switch k.Kind() {
		case reflect.String:
			{
				e.addElem(k.String(), v.MapIndex(k), false)
			}
		case reflect.Interface:
			{
				if k.Elem().Kind() == reflect.String {
					e.addElem(k.Elem().String(), v.MapIndex(k), false)
				} else { //not string type?
					e.addElem(k.String(), v.MapIndex(k), false)
				}
			}
		}

	}
}

**Comment by niemeyer** [comment]
We discussed this in the pull request. BSON doesn't support non-string keys.
