### ISSUE TITLE
how to know one session state?

### ISSUE THREAD

**Issue by timeloveboy** [go-mgo/mgo#211]
I wang to define a sessions pool,limited 10 sessions,
how to know each one session state?
我想写一个连接池，如何才能判断每个回话的状态？

**Comment by niemeyer** [comment]
Don't pool sessions.. they are very cheap to create and dispose, and have internal pooling of actual connections. Instead, just use a single master session, configure it as you wish, and then Copy it every time you want a new session, and Close that new session when you're done using it.
