### ISSUE TITLE
Login/Logout Repeatedly

### ISSUE THREAD

**Issue by daaku** [go-mgo/mgo#215]
Hey, I'm still dissecting the issue but wanted to post it here to see if you have any feedback early.

We recently started using Auth with some of our connections, and we're seeing this behavior where the same connection will repeatedly login on the server. From the mongo server perspective we see the same connection ID say `Successfully authenticated as principal...`.

Our usage is typically like this:

```go
func Handler() {
  s := masterSession.New()
  defer s.Close()
  // .. do something with s
}
```

That is we want each request to grab a socket from the pool, use it, and then put it back in the pool. It seems like `Close` calls `LogoutAll`. Upon further investigation it seems like there is a sort of caching built into the driver where `LogoutAll` doesn't actually do it, and in theory if `Login` is called with the same credentials again it should become a no-op. In practice what we're seeing is that `flushLogout` gets called before that happens and so we end up logging in and logging out even though we only ever set the credentials once when we `Dial`.

I'll post more as I keep debugging.

**Comment by daaku** [comment]
I *think* it's `pinger` that's causing `flushLogout` causing us to re-auth every 15s per connection. Still digging.

**Comment by daaku** [comment]
But.. we're seeing it way more often than 15s per connection. Here's some filtered output from the server logs: https://gist.github.com/daaku/468b495b1f96c5027502. For example `conn20627` authenticates 3 times in 1 second.

**Comment by niemeyer** [comment]
Per the documentation, the fundamental difference between [Session.New](http://gopkg.in/mgo.v2#Session.New) and [Session.Copy](http://gopkg.in/mgo.v2#Session.Copy) is that `Copy` will hold on to credentials in use in the copied session, while `New` will not. If you want to re-use login information, please use `Copy`.

**Comment by daaku** [comment]
`Copy` did fix the bulk of them. I had tried it earlier but assumed it didn't work because the pinger was still triggering re-auth once every 15s per connection. That may still be worth fixing.

The docs are also slightly confusing, specifically when I read this bit:

> Login information from the original session will not be copied over into the new session unless it was provided through the initial URL for the Dial function.

I assumed since I only provide login information in `Dial` that the behavior of `New` or `Copy` would be the same for me.

**Comment by niemeyer** [comment]
But you're saying above that you're calling `Login` explicitly.. are you calling it explicitly or not?

**Comment by daaku** [comment]
Sorry, I wasn't clear -- we're not calling `Login` explicitly. We only pass the credentials to `Dial` when we create the initial session.

**Comment by niemeyer** [comment]
The credentials provided to `Dial` are indeed cached, even with `session.New`. Have a look at `copySession` to confirm that the exact same code path that works for `Copy` will keep the original credentials around. `TestAuthURLWithNewSession` in auth_test.go has the test case ensuring it works.

**Comment by michelaquino** [comment]
Hi @daaku, how do you have fix this?

**Comment by daaku** [comment]
We reduced it by using `Copy` instead of `New`, but the pinger still had some overhead. Our product no longer exists so I can't help you much more than unfortunately :/
