### ISSUE TITLE
Connection in pool appears to hang?

### ISSUE THREAD

**Issue by hut8** [go-mgo/mgo#216]
Hey. I'm a bit confused about a bug I've been running into. It's probably in my code :smile: 

Pardon the mess, but here's relevant part 1:
https://github.com/tenex/github-contributions/blob/95219dfcb372fa487b845e089d7c5f7eab4d96c7/ghc-app/main.go#L56

```go
	session, err := mgo.Dial("localhost")
	if err != nil {
		panic(err)
	}
	defer session.Close()
	session.SetMode(mgo.Monotonic, true)
	collection := session.DB("contributions").C("contributions")
	controller := NewGHCController(collection)

	http.ListenAndServe(":5000",
		logHandler(controller))
```

Because you said it was safe to share a `*Session` through multiple goroutines, that's what I'm doing here. I'm creating one `*Session`, getting the `DB` and `Collection` that I want from it, and reusing that to make some simple queries. This was working great for several hours. Then my whole site went down, and I found this in the logs:

```
2016/02/03 06:42:31 http: panic serving 127.0.0.1:54357: read tcp 127.0.0.1:47713->127.0.0.1:27017: i/o timeout
goroutine 2243 [running]:
net/http.(*conn).serve.func1(0xc8200a80b0, 0x7f12110c77e8, 0xc820022078)
        /usr/local/go/src/net/http/server.go:1287 +0xb5
main.(*GHCController).Stats(0xc820011240, 0x7f12110c7c38, 0xc8200a8370, 0xc820096620)
        /home/ghc/go/src/ghc-app/controller.go:118 +0x6b
main.(*GHCController).Stats-fm(0x7f12110c7c38, 0xc8200a8370, 0xc820096620)
        /home/ghc/go/src/ghc-app/controller.go:42 +0x3e
net/http.HandlerFunc.ServeHTTP(0xc8200abeb0, 0x7f12110c7c38, 0xc8200a8370, 0xc820096620)
        /usr/local/go/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc82000ea00, 0x7f12110c7c38, 0xc8200a8370, 0xc820096620)
        /home/ghc/go/src/github.com/gorilla/mux/mux.go:103 +0x270
main.logHandler.func1(0x7f12110c7c38, 0xc8200a8370, 0xc820096620)
        /home/ghc/go/src/ghc-app/main.go:46 +0x600
net/http.HandlerFunc.ServeHTTP(0xc820011a60, 0x7f12110c7c38, 0xc8200a8370, 0xc820096620)
        /usr/local/go/src/net/http/server.go:1422 +0x3a
net/http.serverHandler.ServeHTTP(0xc820014d20, 0x7f12110c7c38, 0xc8200a8370, 0xc820096620)
        /usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8200a80b0)
        /usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:1910 +0x3f6
2016/02/03 06:55:03 http: panic serving 127.0.0.1:54359: read tcp 127.0.0.1:47713->127.0.0.1:27017: i/o timeout
goroutine 2353 [running]:
net/http.(*conn).serve.func1(0xc8200a80b0, 0x7f12110c77e8, 0xc820022078)
        /usr/local/go/src/net/http/server.go:1287 +0xb5
main.(*GHCController).Stats(0xc820011240, 0x7f12110c7c38, 0xc8200a8370, 0xc8200967e0)
        /home/ghc/go/src/ghc-app/controller.go:118 +0x6b
main.(*GHCController).Stats-fm(0x7f12110c7c38, 0xc8200a8370, 0xc8200967e0)
        /home/ghc/go/src/ghc-app/controller.go:42 +0x3e
net/http.HandlerFunc.ServeHTTP(0xc8200abeb0, 0x7f12110c7c38, 0xc8200a8370, 0xc8200967e0)
        /usr/local/go/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc82000ea00, 0x7f12110c7c38, 0xc8200a8370, 0xc8200967e0)
        /home/ghc/go/src/github.com/gorilla/mux/mux.go:103 +0x270
main.logHandler.func1(0x7f12110c7c38, 0xc8200a8370, 0xc8200967e0)
        /home/ghc/go/src/ghc-app/main.go:46 +0x600
net/http.HandlerFunc.ServeHTTP(0xc820011a60, 0x7f12110c7c38, 0xc8200a8370, 0xc8200967e0)
        /usr/local/go/src/net/http/server.go:1422 +0x3a
net/http.serverHandler.ServeHTTP(0xc820014d20, 0x7f12110c7c38, 0xc8200a8370, 0xc8200967e0)
        /usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8200a80b0)
        /usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:1910 +0x3f6
```

So these two lines are what confuse me:

```
panic serving 127.0.0.1:54357: read tcp 127.0.0.1:47713->127.0.0.1:27017: i/o timeout
panic serving 127.0.0.1:54359: read tcp 127.0.0.1:47713->127.0.0.1:27017: i/o timeout
```

These have the same source port, which means they're the same connection, right? What's going on with this particular connection? I am sure that MongoDB was up this entire time (of course I would be getting a connection refused error rather than an i/o timeout otherwise). This error actually repeats hundreds of times over the course of many hours.

When I saw this was happening today, I made this commit: https://github.com/tenex/github-contributions/commit/4b46e1085d9b951ef4ca4aa66b2d54f8f7fb576b which I'm now using in production, but I still don't understand the advantage of using a separate `Session` for each HTTP request, if (as the docs say), the underlying connection pool is copied. So I'm worried that this will continue happening.

Is there's a problem with a single connection in the pool, why isn't it just removed entirely? What am I doing wrong?

Thanks for your help :smiley:

**Comment by niemeyer** [comment]
There are two issues in your original approach: the first one is that you didn't try to recover after a failure. A mgo session, unless in Eventual mode, will not "forget" an error automatically after it happens, as that might potentially mean talking to different servers across serious database crashes without letting the application know that anything happened at all. For recovering such a single session, you may just run session.Refresh() on it to acknowledge the error at a good control point that understands something bad might have happened before the refresh.

The second problem is related to that last part: there's no good control point to acknowledge an error has happened in such a concurrent HTTP request handling server. There may always be logic running in background, and refreshing the session may create havoc. Not only that, but using a single connection also means a long query on one request may affect very badly a completely unrelated request on a different server.

So what you did using multiple sessions and thus multiple underlying connections is correct for your scenario.

**Comment by zygis** [comment]
@niemeyer 
Is this better way
```
session.Refresh()
```
than
```
session.Close()
session = mainSession.Copy()
```
?
