### ISSUE TITLE
TCP connection is not a *net.TCPConn

### ISSUE THREAD

**Issue by frankyin1019** [go-mgo/mgo#217]
Hi, the latest change seems to give us the following error on all our services.
```
panic: internal error: obtained TCP connection is not a *net.TCPConn!?
```

Is it possible to fall back to use a net.Conn instead of a panic?

**Comment by cmoesel** [comment]
We're seeing this too.  It's causing our Travis builds to fail (e.g., https://travis-ci.org/intervention-engine/ie/builds/107332068).

**Comment by mpobrien** [comment]
Sounds like the same issue as #218 - the fix for it was released in the v2 branch.

**Comment by cmoesel** [comment]
I can confirm that with the fix in v2, my Travis builds no longer fail.

**Comment by niemeyer** [comment]
That was addressed a couple of days ago and released by then. Really sorry for the trouble folks.
