### ISSUE TITLE
mgo and ipv6 failure due to mongo bug

### ISSUE THREAD

**Issue by voidspace** [go-mgo/mgo#22]
Due to a bug in mongo, now fixed in 2.7.4, when creating replicasets with ipv6 we *must* specify the address in the form "::1:port", not the more correct "[::1]:port". 

https://jira.mongodb.org/browse/SERVER-5436

mgo, in resolveAddr (in cluster.go, called from syncServers), calls net.DialTimeout which fails with "too many colons in address" when we use this format.

This means that starting a replicaset with ipv6 addresses succeeds until a syncServers, which then fails with a "no reachable servers" error (it discards the actual error).

**Comment by niemeyer** [comment]
This was fixed by having resolveAddr not hand out plain addresses to Dial.
