### ISSUE TITLE
Querying object that mimics an error value

### ISSUE THREAD

**Issue by zippoxer** [go-mgo/mgo#221]
I'm using the latest mgo at `gopkg.in/mgo.v2` and MongoDB 3.2.1

When I'm doing this operation (just a basic Apply):

```
var p *SomeStruct
change = mgo.Change{
	Update: bson.M{
		"$set":         p,
		"$setOnInsert": bson.M{"added": time.Now()},
	},
	Upsert:    true,
	ReturnNew: true,
}
info, err := db.C("somecollection").Find(someSelector).Apply(change, p)
```

I get this blank error:
```
&mgo.LastError{Err:"", Code:0, N:1, Waited:0, FSyncFiles:0, WTimeout:false, UpdatedExisting:true, UpsertedId:interface {}(nil), modified:0, ecases:[]mgo.BulkErrorCase(nil)}
```

No message and error code 0, so I can't figure out what's really wrong.

The exact same operation (findAndModify) succeeds through the mongo console.

Why would it return an error when there is none?

Update:

I think figured out the problem.
This is a bug in checkQueryError at session.go. checkQueryError is peeking at the response's raw bytes checking if it has an "err" or "errmsg" before parsing it. Clever trick to avoid parsing, I like it :)
However, my document has a field named "errmsg" and, I guess, my document is included in the response which checkQueryError is searching for "errmsg". When checkQueryError finds "errmsg", it parses the error and since LastError isn't nil (I guess it's unique to successful Apply operations) it returns it as an error, even though there wasn't really an error.

I think the fix would be to check that the LastError's code isn't zero before returning it.

**Comment by niemeyer** [comment]
The test that checks if errmsg exists in the document is just some heuristics to bail early and fast, as that's not for a all query operations. That said, assuming your fix works, that means you have both an "errmsg" value and a "lastErrorObject" value, which means you are storing error values as is, and making it harder for the driver to disambiguate. The fix you propose is probably okay, but it'll have to wait until the next release since this isn't really a recent breakage introduced by the recent driver release. I'd recommend not storing documents that look exactly like an error response if that's possible. Instead, nest them inside a field and everything will be fine. I realize that's suboptimal from an error handling perspective, but the server isn't helping in this case. I hope we can have a much better reporting pipeline in the near future.

**Comment by zippoxer** [comment]
@niemeyer 

I appreciate you paying attention to this.

I'm not storing lastErrorObject. I never knew how lastErrorObject looks like before I dug in session.go to figure out what's wrong.

All I did was keeping a field with the name "errmsg". This field is part of my application logic (I keep information about documents that failed a machine-translation process.)

Now, it's really no big deal for me to $rename it and adapt my application, but I'm thinking what if I couldn't figure out having a "errmsg" field is the problem?

The next person who happens to keep an "errmsg" field might not figure out what's wrong.

Since that's not very likely to happen to someone else soon, I agree with you that this is a low-priority bug.

I love this library nevertheless. This is the first non-standard Go library I took inspiration from :)

**Comment by niemeyer** [comment]
The test you modified says "if result.LastError != nil", so it won't enter this branch unless there's an "errmsg" field *and* LastError (which maps to "lastErrorObject") is not nil.

Can you please verify how that is being the case in your tests?

**Comment by zippoxer** [comment]
You're right. I have no idea why LastError isn't nil. There's really no error - it isn't nil, but it's code is 0 and it's message empty. Also, the (Apply) operation succeeds.

This is the part where my error-like fields are:
```
	"transnote" : {
		"ok" : false,
		"err" : "",
		"errmsg" : "",
		"detections" : [ ]
	},
```

My first test was removing this field from all documents, and when I did, I wasn't getting errors anymore.

So I still can't figure out why LastError isn't nil when this field exists.

I got the same result on two different machines and on both MongoDB 3.0.9 and 3.2.1

**Comment by zippoxer** [comment]
@niemeyer 

I just printed the raw data returned from the server ([here](https://github.com/go-mgo/mgo/blob/v2-unstable/session.go#L3195)), and it's going like this:
```
"lastErrorObject": {
		"n": 1,
		"updatedExisting": true
	},
	"ok": 1,
	"value": {
		// my document...
	}
}
```

There's a lastErrorObject outside of my document and it lacks a code or a message.

Is this normal for Apply operations?

**Comment by niemeyer** [comment]
Yes, but not one with errmsg and lastErrorObject on the same value in a case that is not an error.

Can you send me a small self-contained reproducer? I'm sure I can easily solve that mystery if I manage to see it happening locally.

**Comment by zippoxer** [comment]
```
@niemeyer 

Oops, I indented it incorrectly.

The value, that is my document with the "errmsg" field, is nearby lastErrorObject and not it's child.
checkQueryError is searching the whole response, `value` and `lastErrorObject` included, for "errmsg" and finds the "errmsg" in my document, not in lastErrorObject.

I edited my last comment and fixed the raw response.

Here's a self-contained reproducer for you:

package main

import (
        "gopkg.in/mgo.v2"
        "gopkg.in/mgo.v2/bson"
        "log"
)

func main() {
        sess, err := mgo.Dial("mongodb://localhost/issue221")
        if err != nil {
                log.Fatal(err)
        }
        db := sess.DB("issue221")
        
        // insert test doc
        db.C("docs").Insert(bson.M{"errmsg": ""})
        
        // Apply
        change := mgo.Change{
                Update: bson.M{"$set": bson.M{"x": true}},
        }
        var doc struct {
                Id bson.ObjectId `bson:"_id"`
        }
        info, err := db.C("docs").Find(nil).Apply(change, &doc)
        // log.Print(err != nil)
        log.Printf("info: %#v\n\nerr: %#v\n\ndoc: %#v", info, err, doc)
}
```

**Comment by zippoxer** [comment]
@niemeyer 

Hey, have you had the change to run the reproducer above?

I can successfully reproduce the issue with it, but I just want to make sure it's correct.
