### ISSUE TITLE
How to escape field names that have commas in the bson?

### ISSUE THREAD

**Issue by ElPeque** [go-mgo/mgo#223]
I'd like to do something like this:

EvictionServerPopulatingQueueNotEvictingPages int64 `bson:"eviction server populating queue, but not evicting pages"`

but the comma between 'queue' and 'but' messes with how the tags are split and thus a panic occurs. Is there any solution other than using a map[string]int64 as a parent instead of a struct?

**Comment by niemeyer** [comment]
No, unfortunately there's no alternative for that at the moment, as commas are part of the standard convention for field tags. They separate the field tag from processing options (e.g. "name,omitempty") both in mgo and other standard Go packages. Quotes would also break the parsing similarly.

I would encourage renaming the field, or in the worst case indeed using a map if that's not under your control.
