### ISSUE TITLE
Bson:  `bson:[...]` comments tags are ignored if not set as the first tag. 

### ISSUE THREAD

**Issue by szank** [go-mgo/mgo#224]
For example this: 
```
type TestStruct struct {
Data string `bson:"d",json:"d"`
}
```
works as intended 
this : 
```
type TestStruct struct {
Data string `json:"d",bson:"d"`
}
```
ignores the bson name tags

**Comment by szank** [comment]
Update : 
I guess I was overzealous yesterday. 
It turned out that this : 
```
type TestStruct struct {
Data string `json:"d",bson:"d"`
}
``` 
doesn't work, but this : 
```
type TestStruct struct {
Data string `json:"d" bson:"d"`
}
```
does. Strangely enough go vet doesn't complain about it. I will double check the code and possibly raise an issue in the golang repo.

**Comment by niemeyer** [comment]
Yes, the latter is indeed the correct format for field tags that follow the usual convention.

Thanks for reaching out, though.
