### ISSUE TITLE
auto populate dbrefs

### ISSUE THREAD

**Issue by alioygur** [go-mgo/mgo#225]
Hello

is there any way to auto populate DBRefs ? like mongoose's http://mongoosejs.com/docs/populate.html ?

**Comment by zygis** [comment]
Mongoose is not a mongodb driver like mgo. 
```
Mongoose is a MongoDB object modeling tool
```

**Comment by niemeyer** [comment]
There's no way to do that, and there likely won't be in the foreseeable future.

Here is some background for why, from a mailing list conversation a couple of years ago:

https://groups.google.com/d/msg/mgo-users/ZERwp33nnAM/nSBwZb0YK1IJ

**Comment by alioygur** [comment]
@niemeyer what is your approach one-to-many modeled collections on mongo db?

I have these models, and I want to get all posts with their users

please help me about that.

```go
type Times struct {
	CreatedAt time.Time `bson:"CreatedAt"`
	UpdatedAt time.Time `bson:"UpdatedAt"`
}

// User model
type User struct {
	ID          bson.ObjectId   `bson:"_id,omitempty"`
	Username    string          `bson:"Username,omitempty"`
	Email       string          `bson:"Email,omitempty"`
	Password    string          `bson:"Password,omitempty"`
	IsActivated bool            `bson:"IsActivated,omitempty"`

	Times `bson:",inline"`

	Posts []*Post `json:",omitempty" bson:"-"`
}

// Post model
type Post struct {
	ID          bson.ObjectId `bson:"_id,omitempty"`
	UserID      bson.ObjectId `bson:"UserID,omitempty"`
	ImageID     bson.ObjectId `bson:"ImageID,omitempty"`
	Title       string        `bson:"Title,omitempty"`
	Slug        string        `bson:"Slug,omitempty"`
	Description string        `bson:"Description,omitempty"`

	Times `bson:",inline"`

	User *User `bson:"-" json:",omitempty"`
}
```

**Comment by niemeyer** [comment]
This is either done in two steps, query one and then query the other, or it may be done with $lookup in more recent server versions. The latter is much more complex, though, so I'd start with the former.

**Comment by alioygur** [comment]
@niemeyer thank you.

**Comment by niemeyer** [comment]
No problem. Note you can/should batch them (query a bunch of posts, then a bunch of users), rather than interleaving one by one. The latter would perform quite poorly.

**Comment by alioygur** [comment]
but in this case how I bind User to Post's User?

Now, I am using like this

```go
func FindPostsWithUser(sess *mgo.Session) (posts []*domain.Post, err error) {
	err = C(TblPosts, sess).Find(nil).All(&posts)

	if err != nil {
		return
	}

	for _, post := range posts {
		if post.UserID.Valid() {
			C(TblUsers, sess).FindId(post.UserID).One(&post.User)
		}
	}

	return
}
```

github repo link https://github.com/alioygur/goaligo/blob/master/app/services/post.go#L22

**Comment by ZeuCxb** [comment]
@alioygur how you bind?
