### ISSUE TITLE
Where does this strange "error parsing" come from?

### ISSUE THREAD

**Issue by d3sire** [go-mgo/mgo#235]
Code to reproduce can be found [here](https://gist.github.com/d3sire/628d4cd180ad9a6cad0d).

Any help is appreciated.

**Comment by niemeyer** [comment]
What is the full error message, and which line is originating it?

**Comment by d3sire** [comment]
@niemeyer I suppose its Run() line.
Full output:
`error parsing element 0 of field documents :: caused by :: wrong type for '0' field, expected object, found 0: [ { name: "Ale", phone: "+55 53 1234 43210", timestamp: new Date(1456889581057) }, { name: "Ale", phone: "+55 53 1234 43211", timestamp: new Date(1456889581057) }, { name: "Ale", phone: "+55 53 1234 43212", timestamp: new Date(1456889581057) }, { name: "Ale", phone: "+55 53 1234 43213", timestamp: new Date(1456889581057) }, { name: "Ale", phone: "+55 53 1234 43214", timestamp: new Date(1456889581057) } ]`

**Comment by niemeyer** [comment]
I see the problem. You really want this instead:

	bulk := c.Bulk()
	bulk.Unordered()
	for i := 0; i < 5; i++ {
		phone := "+55 53 1234 4321" + strconv.Itoa(i)
		people[i] = Person{
			Name: "Ale", Phone: phone, Timestamp: time.Now()}
	bulk.Insert(&people)
	}

**Comment by d3sire** [comment]
@niemeyer  It didn't change anything.

**Comment by niemeyer** [comment]
It will if you do the suggested change properly. The problem is clear, and the solution was tested and works here.

**Comment by d3sire** [comment]
@niemeyer  I got the idea from what you have posted. But I think that you really meant this:
```golang	
     for i := 0; i < 5; i++ {    
		phone := "+55 53 1234 4321" + strconv.Itoa(i)
		person := Person{
			Name: "Ale", Phone: phone, Timestamp: time.Now()}
		bulk.Insert(&person)
     }
```

**Comment by niemeyer** [comment]
That's exactly what I posted above. :)

Being a pointer or not makes no difference for mgo. Try both and you'll see both work.

**Comment by d3sire** [comment]
@niemeyer I really appreciate your help. But please, don't change you message and tell that you have posted that from the beginning. I have already said that I got what you have meant.

**Comment by niemeyer** [comment]
@d3sire Heh.. you're welcome, rude dude.

**Comment by d3sire** [comment]
@niemeyer I am not rude. You are rude. 
![proof](http://i.imgur.com/D5gn2AI.png)

**Comment by niemeyer** [comment]
You're still welcome, @d3sire.
