### ISSUE TITLE
'fatal error: sasl/sasl.h: No such file or directory' when deploying app to Heroku

### ISSUE THREAD

**Issue by grsouza** [go-mgo/mgo#242]
Hello everyone, I'm trying to deploy my app to Heroku and I'm using godeps for dependency management like their docs suggested. But when I `git push heroku master` I get the following error:
```
remote: github.com/grsouza/feeng-api/vendor/gopkg.in/mgo.v2/internal/sasl
remote: # github.com/grsouza/feeng-api/vendor/gopkg.in/mgo.v2/internal/sasl
remote: vendor/gopkg.in/mgo.v2/internal/sasl/sasl.go:15:24: fatal error: sasl/sasl.h: No such file or directory
remote:  // #include <sasl/sasl.h>
remote:                         ^
remote: compilation terminated.
```

Could someone help me?

Thanks in advance.

**Comment by besser** [comment]
I got this same error in Heroku and in Linux when I do `go get` in my project!

**Comment by besser** [comment]
Hey, I try to use `godep save` only, instead `godep save ./...` and the deploy to Heroku was succefuly!

**Comment by niemeyer** [comment]
If you want to compile it with SASL support, that depends on C libraries and headers that need to be available in the build system and in the runtime system:
```
% dpkg -S /usr/include/sasl/sasl.h 
libsasl2-dev: /usr/include/sasl/sasl.h
```

**Comment by ista-samanta** [comment]
In my case, I have installed **cyrus-sasl-sql** package using yum. After that go get ./... worked fine. I am using centos 7 and go 1.7 I
