### ISSUE TITLE
replicaSet seems to be interpreted as part of the db name

### ISSUE THREAD

**Issue by bejayoharen** [go-mgo/mgo#247]
When I try to use the replicaSet parameter as part of the mongo URL, I get the following error:

    not authorized on shimmeo?replicaSet=rs-ds045940 to execute command

This seems to suggest that it thinks the database name is `shimmeo?replicaSet=rs-ds045940`, when, in fact, the database name is simply `shimmeo` -- the `?replicaSet=rs-ds045940` should be interpreted as a parameter. I was previously running an old version of mgo, so I purged it. I've updated to the latest version of the driver with

    go get gopkg.in/mgo.v2

and updated my includes.

The documentation in the source code for the driver seems to indicate that the replicaSet parameter is supported, which makes me think I'm doing something wrong, but I don't know what that might be.

    //     replicaSet=<setname>
    //
    //         If specified will prevent the obtained session from communicating
    //         with any server which is not part of a replica set with the given name.
    //         The default is to communicate with any server specified or discovered
    //         via the servers contacted.

Here's the error:

    2016-03-19T17:10:27.052129+00:00 app[web.1]: ERROR 2016/03/19 17:10:27 future.go:85: Error running future: not authorized on shimmeo?replicaSet=rs-ds045940 to execute command { count: "FUTURE", query: { executeafter: { $lte: new Date(1458407427049) } } }
    2016-03-19T17:10:27.060040+00:00 app[web.1]: ERROR 2016/03/19 17:10:27 mongoutil.go:95: not authorized on shimmeo?replicaSet=rs-ds045940 to execute command { createIndexes: "FUTURE", indexes: [ { name: "executeafter_1", ns: "shimmeo?replicaSet=rs-ds045940.FUTURE", key: { executeafter: 1 }, background: true } ] }
    2016-03-19T17:10:27.060151+00:00 app[web.1]: ERROR 2016/03/19 17:10:27 mongoutil.go:96: {[executeafter] false false true false 0  0 0 0 0 0 0   map[]}
    2016-03-19T17:10:27.062398+00:00 app[web.1]: panic: Could not setup Mongo index FUTURE

Here's the function that produces the error:

    func SetupMongoIndices() {
	session, err := mgo.Dial(mongouri)
	if err != nil {
		panic("Could not setup Mongo indices")
	}
	session.SetMode(mgo.Monotonic, true)
	defer session.Close()

	for i, _ := range indexIndices {
		collection := session.DB(mongodb).C(indexCollectionNames[i])
		err = collection.EnsureIndex(indexIndices[i])
		if err != nil {
			revel.ERROR.Print(err)
			revel.ERROR.Print(indexIndices[i])
			panic("Could not setup Mongo index " + indexCollectionNames[i])
		}
	}
    }

**Comment by niemeyer** [comment]
Can you please provide a full self-contained example that I can run locally? I suspect that as you do that, you'll find out that this is not really how the string is reaching the driver.

Here is some evidence that the URL parsing works as it should:

```
        url, _ := mgo.ParseURL("shimmeo?replicaSet=rs-ds045940")
        fmt.Printf("%#v\n", url)
```

Outputs:

```
&mgo.DialInfo{Addrs:[]string{"shimmeo"}, Direct:false, Timeout:0, FailFast:false, Database:"", ReplicaSetName:"rs-ds045940", Source:"", Service:"", ServiceHost:"", Mechanism:"", Username:"", Password:"", PoolLimit:0, DialServer:(func(*mgo.ServerAddr) (net.Conn, error))(nil), Dial:(func(net.Addr) (net.Conn, error))(nil)}
```

That's how `mgo.Dial` parses the URL too.

Please reopen the ticket once you get the reproducer.

**Comment by bejayoharen** [comment]
Thanks for your answer. I suspected I might be doing something wrong -- I think your hint may be enough for me to figure it out. If not, I'll get you that SSCE.

**Comment by bejayoharen** [comment]
Okay, it seems the trouble was with my mongodb variable in this line:

    collection := session.DB(mongodb).C(indexCollectionNames[i])

Sorry for the noise, and thanks again for your help.
