### ISSUE TITLE
Using error instead of panic

### ISSUE THREAD

**Issue by saturn4er** [go-mgo/mgo#253]
In bson you're using panics everywhere, and it's not Go-way (We need to recover them everywhere) [stackoverflow](http://stackoverflow.com/questions/21265464/golang-idiomatic-error-handling). I can create pull request if it necessary

**Comment by niemeyer** [comment]
It's common to use panics to unwind the stack in the internal implementation of such marshaling packages. You should never see them in the library interface, though. As you say, they're recovered at the door, and turned into an error when that's the case. If that's not true, then please open an issue with the specific details and I'll be happy to look into it.
