### ISSUE TITLE
Skip seems to be ignored when used with Apply

### ISSUE THREAD

**Issue by beeker1121** [go-mgo/mgo#262]
In the following query, the same document seems to be returned every time. Kind of pseudo-code.

```go
// Assume 'session' holds the MongoDB session.
col := session.DB("testdb").C("testcol")

skip := 0

change := mgo.Change{
	Update:    bson.M{"$set": bson.M{"active": 1}},
	ReturnNew: true,
}

var d Data{}
for {
	// Find document where active = 0, set to 1 and return atomically.
	_, err := col.Find(bson.M{"active": 0}).Sort("-credits").Skip(skip).Apply(change, &d)
	if err != nil {
		return nil, err
	}

	// Return if the data is ok.
	if time.Now().After(d.Next) {
		return &d, nil
	}

	// Reset active value to 0
	d.Active = 0
	_, err := col.UpsertId(d.Id, d)

	skip++
}
```

The skip value is increasing, yet the same document is returned each time in the loop. I've tried overriding the skip value even and the result is the same - an endless loop.

Is this a bug or am I doing something wrong?

**Comment by beeker1121** [comment]
Just looking at the MongoDB docs, it appears the skip functionality is part of the aggregation pipeline, which afaik doesn't include a way to update.

A way to get around this, for this specific issue, is to first pull the data without Apply, then run the query again with Apply using the document ID.

**Comment by niemeyer** [comment]
For the record, Skip is not just for aggregation, but for querying in general.. it's findAndModify, specifically that has no support for skip:

https://docs.mongodb.org/manual/reference/method/db.collection.findAndModify/
