### ISSUE TITLE
session.Close() does not close first 15 connections

### ISSUE THREAD

**Issue by RongxinZhang** [go-mgo/mgo#264]
Hi Gustavo,

`session.Close()` works fine when I am connected to a single mongo instance.
But if I am connected to a replicaset, It will open 15 connections before closing them down.

Would you know why @niemeyer

### Function
```go
func getMongoServerStatus() bson.M {
  DEV_MONGO_HOST := []string{"127.0.0.1"}
  DB_NAME := "test"
  REPL_NAME := "rs0"

  session, err := mgo.DialWithInfo(&mgo.DialInfo{
    Addrs          : DEV_MONGO_HOST,
    Database       : DB_NAME,
    ReplicaSetName : REPL_NAME,
  })

  if err != nil {
   panic(err)
  }

  defer session.Close()
  session.SetMode(mgo.Monotonic, true)

  result := bson.M{}
  error := session.Run(bson.D{{"serverStatus", 1}}, &result)

  if error != nil {
    panic(err)
  } else {
    return result;
  }
}

func main() {
  const WAIT = 1 * time.Second;
  for {
    getMongoServerStatus()
    time.Sleep(WAIT)
  }
}
```

### Mongod logs
<img width="983" alt="screen shot 2016-04-29 at 12 00 42 pm" src="https://cloud.githubusercontent.com/assets/3782456/14926663/0b3ce60c-0e02-11e6-897f-d1a8b60d7784.png">

**Comment by niemeyer** [comment]
session.Close has no relationship to connection closing. It will simply put any reserved sockets (if any) back into the pool. With more concurrency, more connections are open. If there are more replica sets to coordinate, there will be more internal concurrency too, even if the application logic outside the driver is not doing so.

**Comment by RongxinZhang** [comment]
@niemeyer thanks for the reply!
 I have 3 replicas that, should mgo on open 3 connections? why does it open 15?

**Comment by niemeyer** [comment]
These 15 connections are definitely not from the driver alone. It does open just three connections if all you do is connect to a replica set. Once you start using the driver, though, and it needs to synchronize further with the servers, it may open more connections.

I suggest performing some tests to see what's going on there.

**Comment by RongxinZhang** [comment]
@niemeyer ok thanks! I'll look into this ✌️
