### ISSUE TITLE
Unable to cast object of type 'MongoDB.Bson.BsonDocument' to type 'MongoDB.Bson.BsonBoolean'

### ISSUE THREAD

**Issue by anweiss** [go-mgo/mgo#265]
I just started noticing an odd error when I execute the following simple insert request:

```go
c := session.DB("dbname").C("collectionname")
err := c.Insert(bson.M{"key": "value"})
```

This results in the following error:

```
Unable to cast object of type 'MongoDB.Bson.BsonDocument' to type 'MongoDB.Bson.BsonBoolean'
```

Thoughts?

**Comment by niemeyer** [comment]
This error message is not coming from that piece of code, and it's not coming from the driver either.

Try to copy that piece of code alone into a self-contained file and it will work fine.
