### ISSUE TITLE
Dial should return empty session instead of nil session to allow easier reconnects

### ISSUE THREAD

**Issue by epelc** [go-mgo/mgo#269]
See https://github.com/go-mgo/mgo/blob/v2/session.go#L456-L463

```
    // People get confused when we return a session that is not actually
    // established to any servers yet (e.g. what if url was wrong). So,
    // ping the server to ensure there's someone there, and abort if it
    // fails.
    if err := session.Ping(); err != nil {
        session.Close()
        return nil, err
    }
```

Instead of returning a broken session and an error which would just require a `Refresh()`(or New() or Copy/Clone) all of the Dial\* functions return nil and an error if the initial ping doesn't work.

Now image you have a web server(or anything which doesn't require immediate access to mongodb) and it starts up and you just log mgo connection errors. Because you should still be able to do other things even if you can't initially get a connection to mongodb. All of your route handlers are using `Copy()` on your main mgo session so they automatically reconnect if your database goes down then back up.

Now because the `Dial*` functions return nil instead of a unconnected session(which would work with Copy once mongodb is back up) you have to introduce a mutex or some other complex logic throughout your server. If you want to be able to recover from not being able to initially connect to mongodb.

Timeline
-your server starts and is unable to connect to mongodb
-you get several requests which return errors or basic responses because mongodb is down
-mongodb goes back up
-since all your request handlers or logic using mongodb use `Copy()` your connections are automatically refreshed and your server returns full responses with data from mongodb

This is a bit of a complicated situation but I think it is worth supporting since otherwise your app needs complex logic to reconnect instead of a simple `Copy()`. I think returning the session instead of nil if the first ping fails would be the best fix.

**Comment by niemeyer** [comment]
I was tempted to say no, but reading through the idea is interesting, thanks!  Let me sit on that for a moment thinking about it please.

**Comment by epelc** [comment]
@niemeyer I thought you might say no. Thanks for thinking about it.

The primary issue is that there is no way around this since all of the Dial functions use this and everything on `Session` is internal. I'd be fine with a flag/bool to change the behavior. But I think it'd be safe to change it without adding a flag/bool. I imagine most people either panic on a dial error in which case it would have no affect. The other group are probably logging the error like myself in which case it would either fix the startup issue explained above or at least make it fixable(if they aren't using something like Copy or Refresh at every entrypoint).

**Comment by niemeyer** [comment]
I think we actually cannot change this, unfortunately. Returning a session on error would imply we'd leave the cluster and session alive, which would mean people handling the error as it's supposed to would leak data. We can probably have a different dial setting for doing that, though. Again thinking further...

**Comment by epelc** [comment]
Not sure if this counts. But technically the docs for Dial make no mention of returning a nil session if there is an error. I think it's pretty much a go idiom to return nil on error though.

https://godoc.org/gopkg.in/mgo.v2#Dial

Maybe instead of adding a option to `DialInfo` you could expose some sort of `NewSession` which creates a session without dialing the server(but it would still dial/connect on refresh or Copy()). Not sure if it's worth it, but it might be easier to understand then a config option on `DialInfo`. I'm not sure how much time this would be take though.

**Comment by niemeyer** [comment]
> Not sure if this counts. But technically the docs for Dial make no mention of returning a nil session if there is an error. I think it's pretty much a go idiom to return nil on error though.

I don't understand the point. Yes, it's a very common idiom, a good approach in most cases, and what we do.. !?

> Maybe instead of adding a option to DialInfo you could expose some sort of NewSession

Maybe.. let's think about that a bit further..

**Comment by bamarni** [comment]
@epelc : how are you handling this at the moment? If the connection failure is not critical I don't think it adds much overhead to create a small wrapper, for example : 

``` go
type Db struct {
	Uri     string
	Session *mgo.Session
	mu      sync.Mutex
}

func (db *Db) Init() error {
	db.mu.Lock()
	defer db.mu.Unlock()
	if db.Session != nil {
		return nil
	}

	session, err := mgo.Dial(db.Uri)
	if err != nil {
		return err
	}
	db.Session = session

	return nil
}
```

Then at web application bootup firing an init attempt in the background, otherwise during the first request.

**Comment by epelc** [comment]
@bamarni Not currently handling it. I hadn't thought about wrapping it. I like the idea of wrapping the session and have some sort of session manager/helper handle this type of thing.

**Comment by dmokhov** [comment]
@niemeyer 

Why don't introduce something like `func NewSession(info *DialInfo) *Session` that does exactly the same as `DialWithInfo` except calling `session.Ping()` which is the only source of error as seen from reading the sources?
