### ISSUE TITLE
certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by kerwin** [go-mgo/mgo#297]
Get this when execute `go get labix.org/v2/mgo`

```
https fetch failed: Get https://labix.org/v2/mgo?go-get=1: x509: certificate has expired or is not yet valid
package labix.org/v2/mgo: unrecognized import path "labix.org/v2/mgo" (https fetch: Get https://labix.org/v2/mgo?go-get=1: x509: certificate has expired or is not yet valid)
```

**Comment by niemeyer** [comment]
Thanks, I indeed updated the certificate this weekend. Please note however that this URL is extremely old, and should probably be removed altogether by now. The correct URL for a few years now is `gopkg.in/mgo.v2`.
