### ISSUE TITLE
func (q *Query) All(result interface{}) error returns nil error

### ISSUE THREAD

**Issue by WorkbenchINK** [go-mgo/mgo#301]
If `func (q *Query) One(result interface{}) (err error)` can't find any document it returns `ErrNotFound = errors.New("not found")`, but `All` returns nil. I think this is an issue, as it would be much more logical if `All` also returns `ErrNotFound`

Thanks for a great MongoDB driver!

**Comment by jesselurie** [comment]
Is there a reason for not returning a not found error?
