### ISSUE TITLE
Marshal map[string]interface{}

### ISSUE THREAD

**Issue by firewut** [go-mgo/mgo#321]
Hi there, I've encountered this behaviour:

Golang structure 

```golang
data:map[path:["1" "2" "3"]] social_account:map[fb_id:1234]
```

Operation executed `Collection.Insert(d)`. Resulting MongoDB document:

```
{"data" : {
    	"path" : [
			"\"1\"",
			"\"2\"",
			"\"3\""
		]
	},
	"social_account" : {
		"fb_id" : "1234"
	}
}
```

My test failed after I pulled mgo.v2 a few hours ago. Tomorrow I'll rollback a few commits to find a hash where it used to work. 

Environment: Golang 1.7
MongoDB: 3.2.8
mgo.v2 - latest commit

**Comment by niemeyer** [comment]
Hi Andrey,

Did you find out what the issue was?

**Comment by firewut** [comment]
Yes, it was my test issue. Was hard to find, but I fixed it. 
mgo works perfect :)
