### ISSUE TITLE
omitempty doesn't work on DBRef ?

### ISSUE THREAD

**Issue by narup** [go-mgo/mgo#326]
Hello Team,

I am new to both Go and Mgo, trying to write some MongoDB interaction using Mgo. What I have is 

```
type User struct {
    BaseData      `bson:",inline"`
    FullName       string            `json:"fullName" bson:"fullName" binding:"required"`
    Email              string            `json:"email" bson:"email" binding:"required"`
    Password       string            `json:"password" bson:"password" binding:"required"`
    Promo            mgo.DBRef   `json:"promo" bson:"promoCode`
}
```

Promo in this case is optional, so I don't want to insert anything if it's not present in User data. Rather, I see it inserted as `"promo" : DBRef("", null)`  But, if I use `bson:"promoCode, omitempty`` I get unsupported tag or some error like that. 

If I use pointer reference, `Promo *mgo.DBRef` then it inserts `"promo":null` But, I am trying to see if I can completely ignore it.

Am I missing anything? Thanks

**Comment by asaf** [comment]
Anyone?

**Comment by hexadecy** [comment]
Manual references are preferable to DBREFs. DBREFs are helpful when the referenced object lives in another database or where the collection name would not otherwise be obvious.

Denormalization/embedding is preferable to any kind of linking because then you get atomic updates and don't need to re-query for the related data.

**Comment by niemeyer** [comment]
I believe the issue is simply that the tag has an extra space which shouldn't be there.

Try to use `bson:"promo,omitempty"` as the field tag.

Note that there's nothing special about `DBRef` here. `mgo/bson` is supposed to handle structs fine in these cases, and `DBRef` is just a normal struct.

**Comment by hexadecy** [comment]
@narup did it fix this issue?

**Comment by narup** [comment]
Yes sorry, @niemeyer is correct.
