### ISSUE TITLE
Is this repository even still active  ?

### ISSUE THREAD

**Issue by logicaleak** [go-mgo/mgo#372]
Latest commit is on 1st of august, and surprisingly this seems to be the only solution for mongodb

**Comment by niemeyer** [comment]
Yes, It's well mainrained and loved.

**Comment by logicaleak** [comment]
Is that why you picked to answer this useless issue instead of millions of legitimate ones ?

**Comment by niemeyer** [comment]
Yes, this one is trivial to close with the time I have available right now.

Thanks for your understanding. Hope you enjoy the driver.
