### ISSUE TITLE
will it support for Geospatial  

### ISSUE THREAD

**Issue by selvam347** [go-mgo/mgo#377]
Currently i am using [https://github.com/GoRethink/gorethink](url). As rethinkdb and go driver stops it's support, i am planning to move my DB to mongodb. Current project needs support of geospatial commands. will mgo support geospatial command? if so, where can i find documents.

**Comment by niemeyer** [comment]
Yes, that works fine. I suggest having a look at the documentation for MongoDB proper, as most details are general across the drivers.
