### ISSUE TITLE
If bson.ObjectIdHex() is passed to Find() error is "not found".

### ISSUE THREAD

**Issue by omani** [go-mgo/mgo#388]
Hi,

```go
var file bson.M

myid := bson.ObjectIdHex(query["id"])
err := ds.gridFS().Find(bson.M{"_id": myid}).One(&file)
...
```

the above code snippet shows how I query by objectids. the correct objectid in query["id"] is not found when passed to `Find()` as an `ObjectIdHex()` objectid. query["id"] is a string representation of an objectid like "453534533453342...".

any ideas why I get this issue?

**Comment by omani** [comment]
I've checked the same document by querying differently. so I got the document. printed the id of both the fetched document and my actual query["id"] and both were the same.

but querying the same document, with the same objectid generated from bson.ObjectIdHex(query["id"]) results in a "not found" error.

I am really starting to think that `bson.ObjectIdHex()` is broken.

**Comment by hexadecy** [comment]
This is not an issue, you should've post in a forum.

err := ds.gridFS(**"fs"**).Find(bson.M{"_id": myid}).One(&file)

    func (db *Database) GridFS(prefix string) *GridFS
GridFS returns a GridFS value representing collections in db that follow the standard GridFS specification. The provided prefix (sometimes known as root) will determine which collections to use, and is usually set to "fs" when there is a single GridFS in the database.

**Comment by omani** [comment]
no. look closely. it's `gridFS()` not `GridFS()`.

I am using a wrapper method:
```go
func (ds *GridFSDataStore) gridFS() *mgo.GridFS {
	ds.session.Refresh()
	return ds.db().GridFS("fs")
}
```

**Comment by omani** [comment]
```go
logrus.Info(file["_id"])
logrus.Info(bson.ObjectIdHex(query["id"]))
logrus.Warn(file["_id"] == bson.ObjectIdHex(query["id"]))```

outputs:
`false` for the comparison.

so after fetching the document by querying for another field than id I thought why not compare the two objectids. and I think here is the problem:

the file["_id"] from the fetched document is not the same as the given query. but when I look at the two objectids with my eyes I *see* they are the same.

```go
INFO[0000] ObjectIdHex("58842e38b1c2f97747487e66")
INFO[0000] ObjectIdHex("58842e38b1c2f97747487e66")
WARN[0000] false
```

**Comment by omani** [comment]
it gets even more weird:

```go
logrus.Info(file["_id"])
logrus.Info(bson.ObjectIdHex(query["id"]))
logrus.Warn(reflect.TypeOf(file["_id"]), reflect.TypeOf(bson.ObjectIdHex(query["id"])))
logrus.Warn(reflect.TypeOf(file["_id"]) == reflect.TypeOf(bson.ObjectIdHex(query["id"])))
logrus.Warn(file["_id"] == bson.ObjectIdHex(query["id"]))
```

outputs:
```
INFO[0000] ObjectIdHex("58842e38b1c2f97747487e66")
INFO[0000] ObjectIdHex("58842e38b1c2f97747487e66")
WARN[0000] bson.ObjectId bson.ObjectId
WARN[0000] false
WARN[0000] false
```

**Comment by hexadecy** [comment]
Ok, it looks to be a different type.
type string != type bson.ObjectId
"ObjectIdHex("58842e38b1c2f97747487e66")" != bson.ObjectId{"
58842e38b1c2f97747487e66"}

2017-01-22 11:50 GMT-05:00 Hasan Pekdemir <notifications@github.com>:

**Comment by omani** [comment]
ok so how can I pass the "string" query["id"] into `Find()` then? Even doing a `bson.ObjectIdHex()` before doesn't seem to solve this issue.

so any hints?

**Comment by hexadecy** [comment]
Try directly with the id...
err := ds.gridFS().Find(bson.M{"_id": bson.ObjectIdHex("551eecbbb726c80f68000087")}).One(&file)

**Comment by omani** [comment]
I did. not found.

**Comment by omani** [comment]
could you please try this out in some code and try to reproduce this? I am starting to think that `bson.ObjectIdHex()` is broken.

**Comment by omani** [comment]
Ok I just found the issue:

"gopkg.in/mgo.v2/bson" != "labix.org/mgo/v2/bson"

my imports were wrong.

**Comment by omani** [comment]
this is a layer 8 problem. I really apologize for the waste of time of you and myself.
