### ISSUE TITLE
Get ObjectId on insert

### ISSUE THREAD

**Issue by facundomedica** [go-mgo/mgo#392]
I've tried searching this and found many answers for the same question. Is it correct to make an ObjectId and then inserting the document? Can you give an example?

Until now I've been inserting then querying the same document to get the ObjectId.

**Comment by hexadecy** [comment]
```
c := session.DB("test").C("people")

var p = Person{
  ID: bson.NewObjectId(),
  Name: "Bill",
}
_, err = c.UpsertId(p.ID, &p)
```

**Comment by facundomedica** [comment]
Great answer, just what I wanted to know! Closing the issue!
