### ISSUE TITLE
Custom SetBSON help

### ISSUE THREAD

**Issue by yefim** [go-mgo/mgo#401]
I have a user document in mongo that looks like this:
``` javascript
{
  "email": "test@example.com",
  "courses": [
    {
      "subject": "Math"
    }
  ],
  "tests": [
    {
      "name": "SAT"
    }
  ]
}
```

I want to decode that user into structs that look like:

``` go
type User struct {
  Email     string `bson:"email"`
  Portfolio Portfolio
}

type Portfolio struct {
  Courses []Course `bson:"courses"`
  Tests   []Test   `bson:"tests"`
} 

type Course struct {
  Subject string `bson:"subject"`
}

type Test struct {
  Name string `bson:"name"`
}
```

Notice that I'm trying to add a `Portfolio` abstraction so that I can get a user's courses via `user.Portfolio.Courses`.

I'm fetching users via
``` go
user := User{}

session.DB("app").C("users").Find(bson.M{"email": "test@example.com"}).One(&user)
```

How do I write the bson tags for Portfolio and how do I write the custom SetBSON to use the []Course and []Test setters? Thank you in advance.

**Comment by benpaxton-hf** [comment]
Based on the documentation, you don't need a custom `SetBSON()`, just add a ``` `bson:",inline"` ``` tag to the `Portfolio` field of the struct:

```go
type User struct {
  Email     string    `bson:"email"`
  Portfolio Portfolio `bson:",inline"`
}
```

I don't remember if this is implied by an embedded struct, but the following might work too:
```go
type User struct {
  Email     string `bson:"email"`
  Portfolio
}
```

**Comment by yefim** [comment]
Thanks @benpaxton-hf! The `inline` tag worked for me!
