### ISSUE TITLE
 go get gopkg.in/mgo.v2 stuck

### ISSUE THREAD

**Issue by vkuznet** [go-mgo/mgo#405]
Hi,
I experience weird problem that  go get gopkg.in/mgo.v2 command stuck forever. It happens on AFS file system. I can't find any specific flag for go get command to get verbose output that I can look what causing this problem, but it is really annoying since we can't integrate mgo in our usual build system. I'll be happy to check anything and resolve the problem if you'll give some instructions. 
Thanks,
Valentin.

**Comment by smoya** [comment]
@vkuznet you can use the `-v` flag.
Btw, this is my output (It works fine).

```
$ go get -v gopkg.in/mgo.v2
gopkg.in/mgo.v2/internal/scram
gopkg.in/mgo.v2/internal/json
gopkg.in/mgo.v2/bson
gopkg.in/mgo.v2
```

**Comment by vkuznet** [comment]
This is what I see:

```
lxplus085(15:32:02)> time go get -v gopkg.in/mgo.v2
Fetching https://gopkg.in/mgo.v2?go-get=1
Parsing meta tags from https://gopkg.in/mgo.v2?go-get=1 (status code 200)
get "gopkg.in/mgo.v2": found meta tag main.metaImport{Prefix:"gopkg.in/mgo.v2", VCS:"git", RepoRoot:"https://gopkg.in/mgo.v2"} at https://gopkg.in/mgo.v2?go-get=1
gopkg.in/mgo.v2 (download)
^C

real    18m4.456s
user    0m0.110s
sys     0m0.037s
```

So, it sits and waits for something, we tried even for longer period of time, e.g. 1h,
and didn't see any progress.

**Comment by smoya** [comment]
Just in case... which version of Go do you use?

**Comment by vkuznet** [comment]
go version go1.7.4 linux/amd64

but I've seen this with 1.6 as well. I mentioned before
that it happens on AFS file system which we use on CERN cluster.

**Comment by hexadecy** [comment]
Can you do `go get gopkg.in/yaml.v1` ?

**Comment by vkuznet** [comment]
Michel,
this I can do:
```
go get -v gopkg.in/yaml.v1
Fetching https://gopkg.in/yaml.v1?go-get=1
Parsing meta tags from https://gopkg.in/yaml.v1?go-get=1 (status code 200)
get "gopkg.in/yaml.v1": found meta tag main.metaImport{Prefix:"gopkg.in/yaml.v1", VCS:"git", RepoRoot:"https://gopkg.in/yaml.v1"} at https://gopkg.in/yaml.v1?go-get=1
gopkg.in/yaml.v1 (download)
gopkg.in/yaml.v1
```

**Comment by vikramj74** [comment]
I am facing the exact same issue, is there a fix available for this ?

**Comment by michaeldebarros** [comment]
I am having the same problem. Guess I will try github.com/globalsign/mgo.

**Comment by niemeyer** [comment]
Sorry for the trouble, but unless there's some more evidence that this is related to mgo or even gopkg.in, there isn't much I can do. There is a network between you and gopkg.in, and multiple moving pieces in between, so "getting stuck" may happen for all kinds of reasons.

If you have actual data that points to an issue in mgo or gopkg.in, please drop me a note and I'll look into it.

**Comment by michaeldebarros** [comment]
@niemeyer is right. I was able to download...a little under 9 minutes or so, but on a fast network. Will try to do it some other times in different network conditions to see. Thanks. And sorry for, what turned out to be, an unrelated issue.

**Comment by iharsuvorau** [comment]
I have a similar issue but only on *alpline* linux using *go1.10*. There are no issues on *OS X 10.11.6* and *debian 9.4*.

Dockerfile:
```
FROM golang:1.10-alpine
RUN apk add --no-cache --update --repository http://dl-3.alpinelinux.org/alpine/edge/testing openssh git
CMD /bin/sh
```

Run the container:
```
docker run -it golang:1.10-alpine
```

Then run inside the container:
```
go get -v gopkg.in/mgo.v2
```

Output:
```
Fetching https://gopkg.in/mgo.v2?go-get=1
Parsing meta tags from https://gopkg.in/mgo.v2?go-get=1 (status code 200)
get "gopkg.in/mgo.v2": found meta tag get.metaImport{Prefix:"gopkg.in/mgo.v2", VCS:"git", RepoRoot:"https://gopkg.in/mgo.v2"} at https://gopkg.in/mgo.v2?go-get=1
gopkg.in/mgo.v2 (download)

### here it hangs for a long time and then fails

# cd .; git clone https://gopkg.in/mgo.v2 /go/src/gopkg.in/mgo.v2
Cloning into '/go/src/gopkg.in/mgo.v2'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
package gopkg.in/mgo.v2: exit status 128
```


Could anyone reproduce the problem?

**Comment by arihantdaga** [comment]
I am facing the same in macOs High Siera..

**Comment by MohitArora1** [comment]
i am facing the same issue in docker.... any fix for this?
