### ISSUE TITLE
Count should return a 64-bit type

### ISSUE THREAD

**Issue by ShaneHarvey** [go-mgo/mgo#412]
The type of `"n"` in MongoDB's response to `count` can be a BSON int, double, or int64 depending on the number of documents, see
https://github.com/mongodb/mongo/blob/r3.4.2/src/mongo/db/commands/count_cmd.cpp#L257-Lundefined
and
https://github.com/mongodb/mongo/blob/r3.4.2/src/mongo/bson/bsonobjbuilder.h#L319-L334

Mgo should use an `int64` to be sure that `"n"` can fit.

**Comment by niemeyer** [comment]
We can't change that in the short term, since that'd be an API change.

If you have that many documents, I'd strongly recommend using a 64bit machine.
