### ISSUE TITLE
mgo doesn't support updating a user without changing their password

### ISSUE THREAD

**Issue by dallbee** [go-mgo/mgo#423]
db.upsertUser() currently requires that either password or passwordHash is set.
This limits the command from being able to update a user's roles without changing their password (or having to store it).

error message: "Must provide a 'pwd' field for all user documents, except those with '$external' as the user's source db"

**Comment by vivace-io** [comment]
Are you certain the user already exists? 

`Database.UpsertUser` falls back to creating a user if it does not already exist. That, in turn, makes a call to Mongo's `db.createUser()` function which requires the password to be set. The error you're seeing is directly from MongoDB, [which you can find here.](https://github.com/mongodb/mongo/blob/master/src/mongo/db/commands/user_management_commands.cpp#L639)

If the user really does not exist, like I suspect, you will need to set the required fields for `Database.UpsertUser`.

If you can ensure that the user does exist, and no spelling errors etc. let me know and I'll take a look!

**Comment by dallbee** [comment]
Appears that your guess is correct. I was looping over users and received a panic on the very first one. That first user happened to be the only user in my collection which did not exist.

Sorry for the frivolous ticket, and thank you for the help!
