### ISSUE TITLE
Format 'gopkg.in/mgo.v2' repo code 

### ISSUE THREAD

**Issue by karpovicham** [go-mgo/mgo#424]
Could you please format the code with `go fmt` command for the [`gopkg.in/mgo.v2`](http://gopkg.in/mgo.v2) repo. 

Here you can check the full current score https://goreportcard.com/report/gopkg.in/mgo.v2
Thanks

**Comment by theodesp** [comment]
I just used go fmt on the latest v2-unstable and it corrected a few lines only. I don't know if its worth it to commit to a PR yet.
