### ISSUE TITLE
Embedded struct fields aren't  properly marshaled 

### ISSUE THREAD

**Issue by NikosEfthias** [go-mgo/mgo#432]
When two structs are embedded json.Marchal properly embeds the fields into the main struct, however, mgo instead of embedding the fields just creates a field and embeds things there.
```go
type A struct{
Name string `json:"name"bson:"name"`
}
type B struct{
A
Surname string `json:"surname"bson:"surname"`
}
```
so if you use json marshaller this b is marshaled as follows
```js
{
"name":"",
"surname":""
}
```
However, the identical bson in MongoDB will look like
```js
{
"A":{
        "name":""
    },
"surname":""
}

```
So is there any way to tell bson marshaler that I want embedded document or do i have to write my structs seperated with a lot of duplicated lines?

**Comment by zhchbin** [comment]
@NikosEfthias Maybe this link will be helpful to you: http://stackoverflow.com/a/20854693

```golang
type A struct{
        Name string `json:"name"bson:"name"`
}

type B struct{
        A `bson:",inline"`
        Surname string `json:"surname"bson:"surname"`
}
```

**Comment by NikosEfthias** [comment]
thank you @zhchbin
