### ISSUE TITLE
Question: 0 Limit

### ISSUE THREAD

**Issue by Nalum** [go-mgo/mgo#443]
Does mgo support the 0 limit?

From the MongoDB [docs](https://docs.mongodb.com/manual/reference/method/cursor.limit/#zero-value):
> A limit() value of 0 (i.e. .limit(0)) is equivalent to setting no limit.

If it's not currently supported is there any plan to support it?

**Comment by pyloque** [comment]
see this
https://github.com/go-mgo/mgo/issues/467

**Comment by Nalum** [comment]
@pyloque I'm not sure these two are related.

**Comment by vivace-io** [comment]
@pyloque this is entirely unrelated, read the docs he linked.

@Nalum yes it does. An example equivelent to the Mongo Docs you linked would be running `Find(someQuery).All(&sliceDestination)`.

Calling `Find(someQuery).Limit(0).All(&sliceDestination)` does **not** result identical behavior as MongoDB does, instead [hitting the default case found here.](https://github.com/go-mgo/mgo/blob/v2/session.go#L2783)

If you're up to it, you may change the title/body to state this as a bug, as I feel that the project itself tends to try to mirror MongoDB's functionality as closely as possible. If not, feel free to close this and I'll open one myself.

**Comment by niemeyer** [comment]
The two issues indeed seem completely unrelated.

@Nalum Yes, setting it to zero will disable the limit.

**Comment by Nalum** [comment]
Thanks @niemeyer

I'll need to verify it is working as expected.

**Comment by niemeyer** [comment]
@Nalum It really should. Not calling SetLimit will already have the limit as zero.

**Comment by Nalum** [comment]
Agreed, I'm probably doing something stupid in my code
