### ISSUE TITLE
ObjectIDs must be exactly 12 bytes long (got 0)

### ISSUE THREAD

**Issue by NikosEfthias** [go-mgo/mgo#444]
```go
type User struct {
	Id             bson.ObjectId `json:"_id,omitempty"bson:"_id,omitempty"`
	Name           string `json:"name"bson:"name,omitempty"`
	Surname        string `json:"surname"bson:"surname,omitempty"`
	ProfilePicture string    `json:"profile_picture"bson:"profile_picture"`
	Username       string `json:"username,omitempty"bson:"username,omitempty"`
	Email          string `json:"email"bson:"email"`
}
func New(email string) *User {
	memberSince := time.Now().Unix()
	usr := new(User)
	usr.Email = email
	usr.MemberSince = memberSince
	usr.Disabled = false
	usr.Frozen = false
	return usr
}
```
My setup is above and what i do is 
```go
        var usr  = user.New(resp.Email)
	if resp.Email == "" {
		usr.Email = resp.Id
	}
        usr.Name = theAccount.Name
	usr.Surname = theAccount.Surname
	usr.Gender = resp.Gender
	usr.ProfilePicture = theAccount.ProfilePicture
	usr.SignUpAccount = theAccount
	usrData, err := usr.Save()
	if err != nil {
		ErrorId := time.Now().UnixNano()
		log.Println(err)
		if er := register.Error(w, _lang.UnknownError, register.ErrorGeneric, ERROR.Save(ErrorId, err.Error())); er != nil {
			logger.Logln(conf.ErrorLogger, "%s", err.Error())
		}
		return
	}
```
And after this operation i get the error `ObjectIDs must be exactly 12 bytes long (got 0)` This is obviously  a bug within mgo since im not even creating the field for `_id`

**Comment by niemeyer** [comment]
The field tags look improperly formatted. There's a space missing there.

An empty tag is indeed an invalid ID, so if the bson package attempts to marshal an empty ID into an object, it will rightfully complain it is not an object ID at all.

**Comment by NikosEfthias** [comment]
i figured the issue out

**Comment by willy182** [comment]
So how to solve it

**Comment by hkoske** [comment]
@NikosEfthias what was the issue?

**Comment by NikosEfthias** [comment]
@hkoske there was a typo in `omitempty` if you say `omitempty` it just works fine since `bson.Objectid` is a string if you don't add `omitempty` it just tries to do something with an empty string

**Comment by udayakumarvdm** [comment]
I have the same issue, I think here everything is okay..
**struct**
> type Article struct {
> 	ID        bson.ObjectId `bson:"_id,omitempty" json:"id"`
> 	Title     string        `bson:"title" json:"title"`
> 	Content   string        `bson:"content" json:"content"`
> 	AuthorID  bson.ObjectId `bson:"author_id" json:"author_id"`
> 	Author    Author        `bson:"author" json:"author"`
> 	CreatedAt time.Time     `bson:"created_at" json:"created_at"`
> }

**Usecase**

> func(a * articleUsecase) Store(c context.Context, m * models.Article)(bson.ObjectId, error) {
>     ctx, cancel := context.WithTimeout(c, a.contextTimeout)
>     defer cancel()
>     m.ID = bson.NewObjectId() // If I don't use this one mean, It will be return empty object id.
>     id,
>     err := a.articalRepositoryInterface.Store(ctx, m)
>     if err != nil {
>         return m.ID, err
>     }
>     m.ID = id
>     return m.ID,
>     err
> }

**Repository**

> func (m *mgoArticleRepository) Store(ctx context.Context, a *models.Article) (bson.ObjectId, error) {
> 	sessionCopy := m.Conn.Copy()
> 	defer sessionCopy.Close()
> 	collection := sessionCopy.DB(DBNAME).C(COLLECTION)
> 	
> 	// create new Artical
> 	err := collection.Insert(&a)
> 	if err != nil {
>              return bson.ObjectId(""), err //Issue arise here
> 	}
> 	return a.ID, nil
> }

Any one can teach me. This is right or wrong way?
