### ISSUE TITLE
go get gopkg.in/mgo.v2 returns unknown path due to no connection could be made

### ISSUE THREAD

**Issue by debapamdas** [go-mgo/mgo#457]
I am trying to get the mgo.v2 package and I'm running into an connection error:

**go get gopkg.in/mgo.v2/bson**
package gopkg.in/mgo.v2/bson: unrecognized import path "gopkg.in/mgo.v2/bson" (https fetch: Get http
13:443: connectex: No connection could be made because the target machine actively refused it.)

I am using windows 7 and behind a corporate firewall
but I am able to get other popular packages like gorilla/mux

**Comment by niemeyer** [comment]
Your firewall might be involved in the issue somehow. Cannot reproduce locally.
