### ISSUE TITLE
difference between copy and clone

### ISSUE THREAD

**Issue by pyloque** [go-mgo/mgo#468]
I search the whole internet, there are lots of discussions,
but still I could not fully understand the difference between clone and copy.

Accoding to the document says, it means there's only just one socket if we use clone,
because  they always share the same socket.

I use reflection technicals to deep insight the field "livingSockets",
it proved that no matter we use copy or clone, there are always lots of livingSockets created.

**Comment by hexadecy** [comment]
Yes, a lots of dicussions about that.
https://github.com/go-mgo/mgo/issues/287
Your session is set to strong or monotonic?
I don't think you should care about this number of sockets.
Clone share ressources and block writes.
Copy use more ressources, but don't block other goroutines.

**Comment by niemeyer** [comment]
This is not an issue or even a question. Please use the mailing list (and look into the history first please, as there are existing discussions on it).
