### ISSUE TITLE
How to create hashed index

### ISSUE THREAD

**Issue by mohsenasm** [go-mgo/mgo#471]
How can i create (or ensure) hashed index?

I need a go code to be equivalent with this:

    >> db.collection.createIndex( { _id: "hashed" } )

  [1]: https://github.com/go-mgo/mgo

**Comment by mwmahlberg** [comment]
Your question was answered at https://stackoverflow.com/questions/45389410/how-to-create-hashed-index-by-mgo-golang by me. Ticket can be closed.
