### ISSUE TITLE
run aggregate queries on secondary in replica set

### ISSUE THREAD

**Issue by romankonz** [go-mgo/mgo#48]
Hi,

while testing a script with different aggregation queries, we  wondered why all aggregation framework queries are sent to the primary.
I took a look at the code, and in the Pipe.Iter method a copy of the session is created and set to strong.
The comment says, it is required when using cursors as result.

https://github.com/go-mgo/mgo/blob/v2/session.go#L1954

What about splitting the old version (without cursor) and the new version (with cursor and enforced strong mode) in two different methods?
Or deciding if i would use a cursor by the interface (pipe.enableCursor(true) e.g.)?

For sure, the best solution would be a cursor that is able to use a monotonic or eventual consistent session, but i don't know if this is possible.

**Comment by romankonz** [comment]
Will this be fixed in future? 

Also i think disabling the cursor when using secondaries like mentioned above is not an option, because then it's not possible to use a secondary for results bigger than 16mb.
This is really important for us for scaling.

**Comment by niemeyer** [comment]
Apologies for the lack of feedback. I believe this is already fixed in the unstable branch and will be in the next release. Will double check.
