### ISSUE TITLE
cannot find inserted documents in the same session

### ISSUE THREAD

**Issue by DrmagicE** [go-mgo/mgo#532]
I try to use insert() method to insert a document  and use find() method to get the inserted document ,but get not found err.Here is my code,can some one tell me where did i go wrong?  

package main

import (
	"fmt"
	"gopkg.in/mgo.v2"
	"gopkg.in/mgo.v2/bson"
)

func main() {
	s, _ := mgo.Dial("localhost") //session
	defer s.Close()
	s.SetMode(mgo.Strong, true)
	session := s.Copy()
	var result map[string]interface{}
	var result1 map[string]interface{}
	c := session.DB("drmagic").C("machine")
	var machineNo string
	var machineType string
	machineNo = "no"
	machineType = "type"
	c.Find(bson.M{"machine_no": machineNo}).One(&result)
	id := bson.NewObjectId()
	if result == nil {
		//not found then insert
		mgoErr := c.Insert(bson.M{"machine_no": machineNo, "machine_type": machineType, "_id": bson.NewObjectId()})
		if mgoErr != nil {
			fmt.Println(mgoErr)
		}
		//find inserted document
		mgoErr1 := c.Find(bson.M{"_id": id}).One(&result1)
		if mgoErr1 != nil {
			fmt.Println("not found！")
		}
	}

}

**Comment by longit644** [comment]
Your inserting code should be `mgoErr := c.Insert(bson.M{"machine_no": machineNo, "machine_type": machineType, "_id": id})`

`bson.NewObjectId()` will return a new ObjectId when you call it.

**Comment by DrmagicE** [comment]
@longit644 Thank you！
