### ISSUE TITLE
Insecure Password Storage

### ISSUE THREAD

**Issue by dbohannon** [go-mgo/mgo#545]
I see that this code-base is not currently supported, but I wanted to make users aware of an issue. While working in the mgo.v2 package, I noticed that the UpsertUser and AddUser functions store the user’s password as an unsalted MD5 digest (see https://github.com/mongodb/mongo-tools/blob/master/vendor/src/gopkg.in/mgo.v2/session.go#L946-L948). MD5 has been considered deprecated for password storage for some time. Additionally, the password should probably be salted with a random, unpredictable value.

**Comment by niemeyer** [comment]
As I've replied to your email days ago, that's not my design. I just implemented the wire protocol required for the server to work at all back then (several years ago).
