### ISSUE TITLE
bson.NewObjectId() not goroutine safe (can generate same value twice)

### ISSUE THREAD

**Issue by klauspost** [go-mgo/mgo#55]
When running a Mongo server under high load I got this error:

```
insertDocument :: caused by :: 11000 E11000 duplicate key error index: db.beacons.$_id_  dup key: { : ObjectId('5492c27614f1661a38000001') }.
```

Since all ID's are generated with bson.NewObjectId(), I didn't expect this to be an issue. However, looking at the code it seems that it doesn't synchronize the random number part between processors, and it does ```i := atomic.AddUint32(&objectIdCounter, 1)```

After a little more digging, I found out that this is not enough to guarantee unique numbers. It seems like a Sync.Mutex is needed for that.

I found this discussion on the topic:

https://groups.google.com/d/msg/golang-nuts/0uPDCRiBWqc/JISqbkl7288J 

>IIUC, atomicity only guarantees memory and CPU cache coherence with 
>regard to the *integrity* of the value being manipulated -- that is, it 
>only guarantees that if one CPU is writing the value while another one 
>is reading it, the second one won't get a value which has some of it 
>bits from the "old" value stored at that memory location before the 
>first CPU started overwriting it, and other bits from the "new" value 
>being written.  What atomicity does not guarantee, is any ordering of 
>observability of values.  I mean, atomic.AddInt32() does only guarantee 
>that what this operation stores at &cnt will be exactly *cnt + 1 (with 
>the value of *cnt being what the CPU executing the active goroutine 
>fetched from memory when the operation started); it does not provide any 
>guarantee that if another goroutine will attempt to read this value at 
>the same time it will fetch that same value *cnt + 1.

**Comment by proteneer** [comment]
The better question is why not let mongod create _id server-side instead?

If bson.NewObjectId() isn't go-routine safe, this is actually a serious bug (granted the only side-effect will be a duplicate document error).

**Comment by niemeyer** [comment]
What you seem to be implying is that [atomic.AddInt32](http://golang.org/pkg/sync/atomic#AddUint32) is not atomic, which is incorrect. It is actually atomic, and the values you get out of it should reflect that, unless there is a serious error in the package which would affect pretty much every application out there.

Consider, for example, that the higher-level logic in the sync package [is implemented](https://github.com/golang/go/blob/0635706849e5fb32741df02ff998db9cb4445da1/src/sync/rwmutex.go#L60) in terms of these functions.

Also consider what Ian Lance Taylor has to say in that thread you refer to:

> Functions like atomic.AddInt32 do a little more than ensuring integrity.  On most processors adding a value to memory requires a read-modify-write memory cycle (this is true even if there is a single  "add to memory" instruction as there on x86).  On a multicore machine  if two cores execute the read-modify-write cycle simultaneously it is  possible for one of the additions to be lost.  atomic.AddInt32 
guarantees that no additions are lost.

So NewObjectId is guaranteed to be safe to run across goroutines. If you have any code that disproves that, I'll be happy to look at it.

**Comment by klauspost** [comment]
Thanks for looking into this. I will do some more digging, and see if I can find the root cause.

**Comment by fungl164** [comment]
Hi, I have run into this situation when generating new object ids in the hundreds of thousands.  Is there any calling convention to guarantee uniqueness?  Will a mutex around the call be enough or do anything at all? Many Thnxs!

**Comment by klauspost** [comment]
It is as safe as it gets as it is implemented now - a mutex should not do any difference. The counter should wrap after 24 bit, which means you should have about 16 million unique keys per second. The mutex may seem to work, since it will likely slow down to a point where you can no longer get >16m keys/sec.

Another thing to be careful of is time adjustments. I have a laptop where the time drifts a lot, and the clock is being adjusted every 5 minutes. This increases the change of collisions when time is adjusted backwards. Just be aware of that.

**Comment by SimonRichardson** [comment]
I've been able to replicate this in our test environment and I've managed to generate a [test case](https://gist.github.com/SimonRichardson/399eab0316e9cae719ca13fe82c64590) for it! 

One thing to be aware of is that it doesn't happen everytime and it's about 1 in 4 for my current setup! More importantly it can generate upto 12gb of garbage whilst doing the test, changing the `routines` to a lower number will reduce this, but you might have to wait more for the collisions to happen.

**Comment by niemeyer** [comment]
There's another part of the object id which is the time. You'd need to wrap the 24-bit value under a second. Pretty unlikely to be the issue by itself.

**Comment by SimonRichardson** [comment]
So it currently seems that the test case is generating roughly 14 million a second on average. Although I doubt we're doing anything close to that for our actual tests.

**Comment by SimonRichardson** [comment]
TBH: I'm unsure of the way forward, other than trying to make a test case of atomic integer collisions :fearful:

**Comment by niemeyer** [comment]
Okay, yes, if you have a tight loop generating those ids and run over 2^24, then it will loop over. That's probably not a realistic issue in actual code, as it'd be pretty hard to insert that many records in one second  from a single instance.

I can try to solve even that case later, though, by implementing certain constraints on the generated ids.
