### ISSUE TITLE
Ability to make instances of Query without an attached session/database/collection

### ISSUE THREAD

**Issue by mpobrien** [go-mgo/mgo#56]
Have run into a lot of cases where this would be useful. Essentially I would like to be able to create instances of mgo.Query without needing to bind it to a specific session/database/collection. The motivation is to segregate the content of the query itself from the connection handling.

This would make it possible to pre-define a bunch of useful queries that contain some business logic for the query itself, pass them around or re-use them, without the session on which the query will be used needing to be in scope.

Something along the lines of this (crude) example:

```go
q := Query{}.Find(makeFilter(...))
                   .Select(fieldsMatching(...))
                   .Sort(getSortFromRequest(...))

// and elsewhere...

err := q.With(collection).All(&out)
```

If you're interested, I'd be happy to work on this and send a pull request with the implementation, if there's any API you'd prefer. Any thoughts?

**Comment by niemeyer** [comment]
The overhead of a second API doing exactly the same thing doesn't sound like a price worth paying. It would just confuse people in exchange for a very small (and perhaps dubious) advantage.

Anything you can abstract away in such an in-memory structure can also be very easily abstracted away into a method that builds the query for you:

    func qWith(c *mgo.Collection) *Query { ... }
