### ISSUE TITLE
Should the driver check for existence of periods (.) in keys?

### ISSUE THREAD

**Issue by proteneer** [go-mgo/mgo#61]
For example, the following is a perfectly valid document that can be inserted:
```
{
    "_id" : "nF3kSsIayjF1d6hrEIKisuvA",
    "value" : {
        "files" : {
            "a.b" : "c.d"
        }
    }
}
```
AFAIK:

http://docs.mongodb.org/manual/reference/limits/#Restrictions-on-Field-Names

This should probably be enforced driver side.

**Comment by niemeyer** [comment]
These characters are accepted in document keys depending on how the document is supposed to be used. For example, a query document can contain $inc as a key with no problems. At the same time, you're right that it is invalid for a document to be stored with one of those keys. But given that it is contextual, we cannot simply change the mgo/bson package to prevent these keys. We'd need a mechanism that validates keys, checking every single field, at marshaling time, and in specific cases only. I'd prefer not to add that overhead for the edge case just to panic on incorrect documents that should not be allows by the application in the first place.

**Comment by jrwren** [comment]
FYI: Documents with these keys cause `db.upgradeCheckAllDBs()` to give an error when checking a mongodb for upgrades. e.g. mongodb 2.4 is upgraded to 2.6 and `db.upgradeCheckAllDBs()` is run and an error is reported for the document.

```
Document Error: document is no longer valid in 2.6 because DottedFieldName: a.b s is not valid for storage.: {
    "_id" : "nF3kSsIayjF1d6hrEIKisuvA",
    "value" : {
        "files" : {
            "a.b" : "c.d"
        }
    }
}
```
