### ISSUE TITLE
Add support for unique index on gridfs file names

### ISSUE THREAD

**Issue by epelc** [go-mgo/mgo#66]
It would be nice if there was support for only allow unique filenames.

Currently you can do this manually by getting the `yourCollect.files` collection and using ensure index. But if you just do this you will leak chunks as there is no index on the chunks(nor enough data to make a unique one). So you need to manually call something like `yourChunkscollection.RemoveAll(bson.M{"files_id": gfile.Id()})` whenever you use `Close()` on a gridFile.

Perhaps more info could be added into the chunks collection about the objects. But I think a better solution would be to support unique filenames in the gridFiles `Close` function. Then the left over chunks could be automatically removed.

Also there is no error exposed for when you attempt to insert an object with a key which has a unique index. You get an error like the following when you do.
```
insertDocument :: caused by :: 11000 E11000 duplicate key error index: 
myDb.myCollection.files.$filename_1  dup key: { : "54bfd23100364516ac000001" }
```

**Comment by niemeyer** [comment]
Close should indeed attempt to remove chunks if there's an error in the final insert in the files collection. I'll fix that.

I don't understand what you mean by that last statement, though. The insert error seems to be exposed as usual. Do you have some sample code?

**Comment by epelc** [comment]
@niemeyer I meant it isn't exposed as a variable so I have to check for it using something like `strings.Contains(err.Error(), "duplicate key error index")`. It's not that useful here but for regular collections with a unique index it would be nice to have.

**Comment by niemeyer** [comment]
You can actually do this:

    mgo.IsDup(err)

The background of this design is that historically there have been several different error codes and messages returned for such duplicated reports.

**Comment by niemeyer** [comment]
Documentation link, for completeness: [IsDup](http://gopkg.in/mgo.v2#IsDup)

**Comment by epelc** [comment]
@niemeyer O thank you I must of overlooked that

**Comment by niemeyer** [comment]
Currently in v2-unstable, will be in v2 once the next release is out.

**Comment by niemeyer** [comment]
Please note that it's probably not a great design to trust on this feature alone for what you intend to do. Ideally there must be a check beforehand that the file does not exist, to avoid unnecessary churn and time spent storing the file.
