### ISSUE TITLE
bson.ObjectId.UnmarshalJSON error on empty value...necessary?

### ISSUE THREAD

**Issue by jraede** [go-mgo/mgo#67]
If I have a struct with a bson.ObjectId property, and I try to unmarshal JSON with a blank string or null value for that field, ObjectId.UnmarshalJSON returns an error. Is there a specific reason for this? IMO it makes more sense to just return a blank invalid ObjectId rather than an error, since many APIs have optional MongoID fields.

**Comment by niemeyer** [comment]
It's not necessary and it's arguably a bug, since during marshaling the ObjectId value is indeed marshaled out as an empty string.

I have fixed it in v2-unstable, which will soon be released under v2.

Thanks for the report.
