### ISSUE TITLE
Adding a server side javascript function.

### ISSUE THREAD

**Issue by egonelbre** [go-mgo/mgo#68]
I'm unable to figure out how to add a [javascript function to a collection](http://docs.mongodb.org/manual/tutorial/store-javascript-function-on-server/). I tried searching for `Save` and `Eval` in the documentation with no luck. Is there some way I missed or is there some workaround to do it?

**Comment by niemeyer** [comment]
If you run this in your shell:

```
> db.system.js.save(
...                    { _id: "echoFunction",
...                      value : function(x) { return x; }
...                    }
...         )
```

And then query the stored value with mgo into a Go map, you'll get this:

    bson.M{
        "_id": "echoFunction",
        "value": bson.JavaScript{Code:"function (x) { return x; }", Scope:interface {}(nil)},
    }

So you can insert, query, etc, these functions using the bson.JavaScript type.

**Comment by egonelbre** [comment]
Thanks, didn't think of querying the table to get the information that I need to insert.
