### ISSUE TITLE
bson.D Map() function doesn't work for nested documents

### ISSUE THREAD

**Issue by deafgoat** [go-mgo/mgo#70]
Calling `Map()` on:

`bson.D{bson.DocElem{"b", 1}}` produces `bson.M{"b":1}`

but on:

`bson.D{bson.DocElem{"b", bson.DocElem{"c", 1}}}` produces `bson.M{"b":bson.DocElem{Name:"c", Value:1}}`.

Would be nice to add recursive support to the `Map()` function.

**Comment by niemeyer** [comment]
The proper syntax for nesting two slices in Go would be:

    bson.D{{"b", bson.D{{"c", 1}}}}

**Comment by niemeyer** [comment]
Sorry, forgot to mention the `Map` side of it: that function does not process its values in any way, being it a map, a slice, or any other value. If you want to obtain the outcome of a value as a map, just marshal and unmarshal it.
