### ISSUE TITLE
Feature Request: bson.ObjectId should implement bson.Getter

### ISSUE THREAD

**Issue by inlined** [go-mgo/mgo#76]
I understand that bson.ObjectId needs to be hard-coded inside bson.Marshal so it can have type code 0x7, but it would be helpful to have ObjectId implement a noop implementation of `GetBSON() (interface{}, error)` which just returns `self, nil`. This allows us to hold ObjectIds in collections of bson.Getters (or interfaces derived from bson.Getter)

**Comment by niemeyer** [comment]
This would generate an infinite loop (the result of GetBSON is still submitted to normal marshaling semantics) and it would also be a strange thing to do for the provided reasoning. bson.Getter tunes marshaling, but it by no means defines what can or cannot be marshaled by bson, which is the implied intent. Said slice should have type []interface{} if it intends to capture values that can be marshaled.
