### ISSUE TITLE
Concurrency issue with find/iterator

### ISSUE THREAD

**Issue by jraede** [go-mgo/mgo#77]
I've constructed a test to determine why our webserver seems to take geometrically longer to serve requests despite being run in go routines. The time for mgo to fetch 50 documents and loop through them all in an iterator increases at the same rate, so it seems like it may be the culprit. I'm wondering if there is something I can tweak to get it to run quicker? Approaching 100 concurrent go routines on my machine I'd expect it to take longer, but it is noticeably increasing at 5, 10, 20, and 50 concurrent requests.

The results I'm seeing from the below benchmark are as follows:

```
1  concurrent finds ::  0 ms/req
5  concurrent finds ::  1 ms/req
10  concurrent finds ::  3 ms/req
20  concurrent finds ::  5 ms/req
50  concurrent finds ::  11 ms/req
100  concurrent finds ::  19 ms/req
200  concurrent finds ::  37 ms/req
```

Here is the benchmark I wrote (to run, place in any folder and run `go test . -v`)

```go
package main

import (
	"fmt"
	"labix.org/v2/mgo"
	"testing"
	"time"
)

var session *mgo.Session

type FooBar struct {
	Name string
}

func runFind(ch chan<- int64) {

	sess := session.Copy()
	defer sess.Close()
	start := time.Now()
	results := sess.DB("mgo_test").C("foobars").Find(nil)
	// connection.Collection("foobars").Collection().Find(nil)

	iter := results.Iter()
	for i := 0; i < 50; i++ {
		t := &FooBar{}
		iter.Next(t)
	}
	// for i := 0; i < info.RecordsOnPage; i++ {
	// 	t := &FooBar{}
	// 	results.Next(t)
	// }
	elapsed := time.Since(start)

	ch <- elapsed.Nanoseconds()

}

func testConcurrentFinds(n int) int {
	ch := make(chan int64)
	for i := 0; i < n; i++ {
		go runFind(ch)
	}

	els := 0
	got := 0

loop:
	for {
		select {
		case elapsed := <-ch:
			els += int(elapsed)
			got++

			if got == n {
				break loop
			}
		default:
			time.Sleep(100 * time.Millisecond)
		}
	}

	return els / n
}

func TestConcurrent(t *testing.T) {
	session, _ = mgo.Dial("localhost:27017")

	DB := session.DB("mgo_test")
	col := DB.C("foobars")
	for i := 0; i < 50; i++ {
		// Create 50 tests
		test := &FooBar{
			Name: "test",
		}

		col.Insert(test)

	}

	nums := []int{1, 5, 10, 20, 50, 100, 200}

	for _, n := range nums {
		tot := 0
		for i := 0; i < 10; i++ {
			tot += testConcurrentFinds(n)
		}
		fmt.Println(n, " concurrent finds :: ", ((tot / 10) / 1e6), "ms/req")
	}
}
```

**Comment by niemeyer** [comment]
How many servers do you have handling those requests, and what is the session mode being used? Also, did you tweak GOMAXPROCS?

**Comment by niemeyer** [comment]
Okay, these details are actually implicit in your described setup. Here is some feedback on it.

The setup indicates that the test is being run using a single core, which means all goroutines are fighting for its time, and it is apparently also using a single MongoDB server, on the local machine. That's not a great way to test parallelism. The connection cache is also cold, which means each test iteration pays the price of establishing new connections for the delta against the last test. So, with that setup it should be expected that increasing the number of requests will increase the cost of handling each request.

Even then, notice that the time is increasing linearly, which means that the time spent is exactly proportional to the work done. If a person can write a book a month, and time shares writing 10 books instead, it'll take 10 times as much to finish the first book, but by then all 10 books will be finished in an ideal scenario (no per book overhead).

Here is a chart for your data:

![image](https://cloud.githubusercontent.com/assets/378683/6377833/d6fd44ca-bd05-11e4-994f-8d37b29abdf7.png)

**Comment by jraede** [comment]
Interesting - thanks for the clarification. I had a hunch that was the case and will now try it on our production-type servers.

**Comment by niemeyer** [comment]
Please remember to adjust GOMAXPROCS. Makes a big practical impact for no additional work on your end.

**Comment by jraede** [comment]
Noted. I didn't know it was set to 1 by default, but that makes total sense.
