### ISSUE TITLE
BSON ID Values And XML/YAML Marshal/Unmarshal

### ISSUE THREAD

**Issue by jackspirou** [go-mgo/mgo#78]
Hi,

When marshaling/unmarshaling to/from XML I noticed that BSON ID values don't render as recognizable strings.  Instead they reader as byte values.

Is there a reason we wouldn't want to include this support with the following methods below in the `bson.go` file?  They are the result of a conversation between @klauspost and @niemeyer here: https://groups.google.com/forum/#!topic/mgo-users/uJqqe_tqCuE

```Go
// MarshalText returns the ObjectId in hex format.
func (id *ObjectId) MarshalText() (text []byte, err error) {
	return []byte(id.Hex()), nil
}

// MarshalText reads the hex value of a marshalled field, and sets the current ID to that value.
// If the value is not a valid hex value, an error is returned
func (id *ObjectId) UnmarshalText(text []byte) error {
	if !IsObjectIdHex(string(text)) {
		return errors.New("invalid bson.ObjectId value")
	}
	*id = ObjectIdHex(string(text))
	return nil
}
```

Sorry if this has already been discussed or resolved.  Thanks in advance!

**Comment by jackspirou** [comment]
I added a pull request with the methods discussed above, but with different comments to match the commenting style currently in `bson.go`:

```Go
// MarshalText turns *bson.ObjectId into an encoding.TextMarshaler.
func (id *ObjectId) MarshalText() (text []byte, err error) {
	return []byte(id.Hex()), nil
}

// UnmarshalText turns *bson.ObjectId into an encoding.TextUnmarshaler.
func (id *ObjectId) UnmarshalText(text []byte) error {
	if !IsObjectIdHex(string(text)) {
		return errors.New("invalid bson.ObjectId value")
	}
	*id = ObjectIdHex(string(text))
	return nil
}
```

**Comment by jackspirou** [comment]
After some testing I noticed that `gopkg.in/yaml.v2` does not marshal a `bson.ObjectId`, even with the above `MarshalText` and `UnmarshalText` methods implemented.

To quickly achieve this I added the method below in my local repo.  While the method below works, what I find strange is that it only works as a method attached to the object itself, instead of a pointer to the object like `MarshalText` and `UnmarshalText` above.

Im guessing this is an implementation difference between the XML encoder/decoder and the YAML encoder/decoder.  I would think that `gopkg.in/yaml.v2` would reflectively identify a value that implements `encoding.TextMarshaler` or `encoding.TextMarshaler`?  Maybe there is a good reason it doesn't?

```Go
// MarshalYAML turns a bson.ObjectId into a yaml.Marshaler.
func (id ObjectId) MarshalYAML() (interface{}, error) {
	return id.Hex(), nil
}
```

I know you might say, "why would anyone want to take a `ObjectId` and marshal it into YAML?" 

If you are working on an API that does its formatted returns by tacking on file type extensions like `api.pets.com/dogs/clifford.json`, you could also have `api.pets.com/dogs/clifford.yml`.  I would argue that as YAML becomes more popular, more and more people will find uses for it - good or bad.

Any thoughts on the subject would be appreciated.

**Comment by jackspirou** [comment]
@niemeyer any thoughts on the above? Thanks!

**Comment by niemeyer** [comment]
You've proposed an implementation in #79, and I asked something there a few days ago. Can you please have a look?

**Comment by jackspirou** [comment]
Will do.  Sorry for the delay, been busy.
