### ISSUE TITLE
bson tag default to customized cases if not set

### ISSUE THREAD

**Issue by sundy-li** [go-mgo/mgo#80]
I propose that bson tag could be customized its  case type rather than lower case, just hold a config variable like `bson.TagLetterCase = "UPPER"  or bson.TagLetterCase = "FIELD"  `, cause I donot want to write many tags in my project model

**Comment by sundy-li** [comment]
Eg, I need to write so many bson:"XXX", but my need is just tag defaults to Filed name
```
 type PreReport struct {
	Id   int    `bson:"Id"`
	Name string `bson:"Name"`
	SiteId int `bson:"SiteId"`
	ProjectId int `bson:"ProjectId"`
	ViewId int `bson:"ViewId"`
	Type int `bson:"Type"`
	Template int `bson:"Template"`
	IsDeleted    bool `bson:"IsDeleted"`
	CreateTime   int  `bson:"CreateTime"`
	CreateUserId int  `bson:"CreateUserId"`
}
```

**Comment by jraede** [comment]
+1. I think that camelCase is much more common than straight lowercase when converting field names to MongoDB properties regardless of language, so at the very least it would make sense to switch that. But the better option would be the above suggestion.

**Comment by jraede** [comment]
Something like this:

```go
const (
	TAG_CASE_LOWER = iota
	TAG_CASE_CAMEL = iota
	TAG_CASE_FIELD = iota
)

// Configure auto tag casing in lieu of a bson tag
var TagCase = TAG_CASE_LOWER

func convertCase(fieldName string) string {
	switch TagCase {
	case TAG_CASE_LOWER:
		return strings.ToLower(fieldName)
	case TAG_CASE_CAMEL:
		return string(unicode.ToLower(rune(fieldName[0]))) + fieldName[1:]
	case TAG_CASE_FIELD:
		return fieldName
	}
	return fieldName
}
```

**Comment by niemeyer** [comment]
We cannot have such a global option, because that'd break everyone else that depends on the current behavior. What may happen at some point is for the default to change so it matches the most common behavior for Go packages, but that can only happen on a major version shift, and it must be considered in terms of the tradeoff of breaking every single application out there.

For the time being, we won't touch this.

**Comment by jraede** [comment]
That's why it would default to lowercase, which is the current functionality. If people want to change it they can but if it defaults to what it is now then there will be no breaking change.

**Comment by niemeyer** [comment]
If you change the default in a global option, you change it for yourself and for all third party packages you are importing, certainly breaking them. No package should expose a global setting that breaks unrelated packages.

**Comment by jraede** [comment]
Ah, got it, didn't think of other packages using mgo. Fair point.

**Comment by sundy-li** [comment]
Fair Point, I didnot notice that too
