### ISSUE TITLE
Support special $comment flag

### ISSUE THREAD

**Issue by mpobrien** [go-mgo/mgo#82]
to enable using these modifiers: http://docs.mongodb.org/manual/reference/operator/query-modifier/#modifiers

**Comment by niemeyer** [comment]
In a way similar to what the shell does, these modifiers are supported by specific methods in the API.

For example:

http://gopkg.in/mgo.v2#Query.Explain
http://gopkg.in/mgo.v2#Query.Hint
http://gopkg.in/mgo.v2#Query.Snapshot

etc.

If there are operations you'd like to see supported and are not, I'll be happy to implement them.

**Comment by mpobrien** [comment]
I'd like to see some kind of support for "$comment" ([details here](http://docs.mongodb.org/manual/reference/operator/meta/comment/)). it's really useful for profiling.

**Comment by niemeyer** [comment]
Sounds good. I'll add that today.
