### ISSUE TITLE
Support SSL

### ISSUE THREAD

**Issue by rgbkrk** [go-mgo/mgo#84]
Love the library, thanks for it. I'm hoping to use it with a Mongo server that uses SSL, passing a mongodb URL like so:

```
mongodb://USERNAME:PASSWORD@iad-mongos2.objectrocket.com:PORT/dbname/?ssl=true
```

This is based on the `url.ssl` section of the [connection string documentation](http://docs.mongodb.org/manual/reference/connection-string/#uri.ssl).

**Comment by niemeyer** [comment]
To connect to an SSL-enabled MongoDB, just define the DialServer 
function in [mgo.DialInfo](http://gopkg.in/mgo.v2#DialInfo), and make use of the tls.Dial [2] to 
perform the connection. 

Please let me know if you need any further details.

**Comment by rgbkrk** [comment]
That's fine, and what we've done so far. It would be nice if we could use the mongo URL parser so we don't have to construct the entire DialInfo object.

```
dialInfo := &mgo.DialInfo{
	Addrs:    []string{c.Settings.MongoURL},
	Database: c.Settings.MongoDB,
	Username: c.Settings.MongoUser,
	Password: c.Settings.MongoPassword,
	DialServer: func(addr *mgo.ServerAddr) (net.Conn, error) {
		return tls.Dial("tcp", addr.String(), &tls.Config{})
	},
	Timeout: time.Second * 10,
}
session, err := mgo.DialWithInfo(dialInfo)
```

**Comment by mhurne** [comment]
I understand the motivation/reasoning behind the approach described above, but I wonder if `ParseURL` could at least parse the `ssl` option and let the caller know what its value was? Perhaps something like:

```
func ParseURL(url string) (*DialInfo, bool, error) {
```

Where the bool is true if the URI included `ssl=true` and `false` otherwise?

When writing a general-purpose client that will be configured using a Mongo URI, the current API requires extracting the `ssl` param from the URI before passing it to `ParseURL` or writing alternative URI parsing logic rather than using `ParseURL` at all. In particular, this is a challenge I've faced in my attempt to tackle https://github.com/hashicorp/vault/issues/362

**Comment by niemeyer** [comment]
Yes, that would be nice. We can error out inside DialWithInfo itself if we receive SSL true, pointing people to some useful documentation.

**Comment by mhurne** [comment]
Great - is this something you have time to pursue? Or would you prefer I take a stab at it and submit a pull request?

**Comment by niemeyer** [comment]
Both are fine. Your contribution will certainly be welcome, but if you want me to do it, please just open an issue for it and I'll take care of it before the next release.

**Comment by mhurne** [comment]
Ok, maybe I'll give it a shot. I was just thinking that perhaps rather than returning a `bool` for the `ssl` flag, it'd be more generally useful for `ParseURL`/`DialInfo` to provide access to all unsupported flags in some way.

**Comment by niemeyer** [comment]
That would mean typos go unperceived.

**Comment by mhurne** [comment]
Sorry, I wasn't clear - by "unsupported flags" I meant flags that are valid according to https://docs.mongodb.org/manual/reference/connection-string/ but not supported by mgo. So it would require knowing what those flags are and extracting them by name. That would allow mgo to continue catching typos/flags that are total gibberish.

**Comment by niemeyer** [comment]
For this case SSL is actually a better term indeed. We actually support SSL, just not without some manual hooking. In the near term I'll probably add a mgo.v2/mgossl package that has a Dial method for some easy defaults. It would reuse that same field from DialInfo.

**Comment by donabrams** [comment]
I hit this same problem when passing a MONGODB_URL to the prometheus exporter. (https://github.com/dcu/mongodb_exporter/blob/master/shared/connection.go#L31).

The amount I have to learn to do the following is high and "just" is not a great description of it's complexity:

> just define the DialServer function in mgo.DialInfo, and make use of the tls.Dial to perform the connection.

I'm going to have to write an awful lot of code to work around this.

**Comment by iamruinous** [comment]
Compose.io has a very helpful article on how to work around this problem. 

https://help.compose.com/docs/connecting-to-mongodb#go--golang-mongodb-and-compose

**Comment by Bartuz** [comment]
@donabrams  if you've solved this problem please share code snippet! Even if it's awful it's still worth to share :)

**Comment by donabrams** [comment]
@Bartuz I gave up on this, sorry. I set up alerts in Atlas and said good enough.

**Comment by Bartuz** [comment]
@donabrams, pair with me! let's solve it!

**Comment by mhurne** [comment]
You can see how this was dealt with in HashiCorp Vault here: https://github.com/hashicorp/vault/blob/master/plugins/database/mongodb/connection_producer.go#L141

**Comment by trucaliber** [comment]
Many thanks.

I used iamruinous' link to https://help.compose.com/docs/mongodb-go-compose for working code.  Replaced my one line mgo.Dial() with 30+ lines to make it work.

**Comment by sokolovstas** [comment]
```
func MgoParseURI(url string, rootCAs *x509.CertPool) (*mgo.DialInfo, error) {
	isSSL := strings.Index(url, "ssl=true") > -1
	url = strings.Replace(url, "ssl=true", "", 1)

	dialInfo, err := mgo.ParseURL(url)

	if err != nil {
		return nil, err
	}

	if isSSL {
		tlsConfig := &tls.Config{}
		if rootCAs != nil {
			tlsConfig.RootCAs = rootCAs
		} else {
			tlsConfig.InsecureSkipVerify = true
		}

		dialInfo.DialServer = func(addr *mgo.ServerAddr) (net.Conn, error) {
			conn, err := tls.Dial("tcp", addr.String(), tlsConfig)
			return conn, err
		}
	}

	return dialInfo, err
}
```

**Comment by gyurobenjamin** [comment]
Still an issue....

**Comment by domodwyer** [comment]
Check out the [README.md](https://github.com/go-mgo/mgo/blob/v2-unstable/README.md)...

**Comment by gyurobenjamin** [comment]
@domodwyer haha thanks. Anyway I fixed it: https://github.com/gyurobenjamin/mgo/commit/887ecb8880385e1c4eea3d5a610f38a00d252ba3

**Comment by levrik** [comment]
@gyurobenjamin Maybe you could open a PR at https://github.com/globalsign/mgo?

**Comment by gyurobenjamin** [comment]
@levrik is it broken there too?

**Comment by levrik** [comment]
@gyurobenjamin SSL doesn't work out of the box there too.

**Comment by domodwyer** [comment]
https://godoc.org/github.com/globalsign/mgo#example-Dial--UsingSSL
