### ISSUE TITLE
Collection.Upsert() with empty map clears out all previous values

### ISSUE THREAD

**Issue by fungl164** [go-mgo/mgo#91]
Not sure if this is a feature or a bug, but running: ```collection.Upsert(sel, change)```
where ```change``` is an empty map causes mongo to clear out all the previously stored field values indiscriminately.

Is this the expected behavior? Thanks!

**Comment by emirpasic** [comment]
That is the expected behaviour. Partial updates should be done through [$set](http://docs.mongodb.org/manual/reference/operator/update/set/). E.g. 

```go
colleciton.Update(sel, bson.M{"$set": bson.M{"change": "new value for change"}})
```

**Comment by fungl164** [comment]
K.  Many Thanks! @emirpasic
