### ISSUE TITLE
Explicit ObjectId on Insert

### ISSUE THREAD

**Issue by emirpasic** [go-mgo/mgo#92]
When running:

```go
input := bson.M{"_id":bson.NewObjectId(), "name":"emir", "job":"developer"}
err = collection.Insert(input)
```

Result in Mongo DB is not ObjectId("hexhexhex"), but some strangely escaped string:

```
{ "_id" : "U,���)p\u0006 \u0000\u0000\u0001", "name" : "emir", "job" : "developer" }
```

I would expect `_id` to be `ObjectId("552ce194ce29701430000002")`

Environment yielding results above:
- mongo db v3.0.2 on centos
- mongo db v3.0.1 on windows 
- mgo v2 (stable)
- go v1.4.1

**Comment by niemeyer** [comment]
An object id is a binary string, which can be represented in hexadecimal or any other useful form. The representation you show above is one such form, and is not indicative of a problem by itself. That said, this is json, which is unrelated to the mgo driver without further context.

If you have code that you believe is misbehaving, please share and we can provide some guidance.

**Comment by byrnedo** [comment]
@emirpasic did you get this resolved? I'm facing the same issue http://stackoverflow.com/questions/31244438/mgo-newobjectid-corrupt-on-insert

**Comment by emirpasic** [comment]
@byrnedo Nope, I ignored the issue and worked around it by creating my own "id" for each document instead, thus did not use the possibly mangled "_id" (ObjectId).

I don't quite agree that this is a presentation issue, i.e. hexadecimal vs binary string as the author suggests, since I don't get a consistently expected behaviour when:
1. Insert document with "_id" equal to ObjectId("552ce194ce29701430000002")
2. Find document with "_id" equal to ObjectId("552ce194ce29701430000002") 
(2.) just does not happen, can't find it and when I directly connect to mongo and search for that document, then I encounter this issue of { "_id" : "U,���)p\u0006 \u0000\u0000\u0001" whereas documents I insert directly through the mongo client show a more readable hexadecimal value.

**Comment by niemeyer** [comment]
This is most likely a bug in your application, possibly caused by an issue similar to the one @byrnedo reported (see StackOverflow link and my response there). If you insert a string, you'll get a string, if you insert a `bson.ObjectId`, you'll get an `ObjectId`.

If you have any code showing otherwise, I'd be very happy to have a look at it.

**Comment by emirpasic** [comment]
After reading final comment of @byrnedo on StackOverflow, it could be that I am facing the same issue of path confusion.

**Comment by byrnedo** [comment]
Thanks for getting back to me @emirpasic, yeah I just ended up standardising the import paths and has been working since.
