### ISSUE TITLE
it's support mongodb 3.0 authentication?

### ISSUE THREAD

**Issue by williambao** [go-mgo/mgo#94]
When I upgrade my mongodb server to version 3.0 from 2.6 it can't connect from golang use mgo.

I add 'authMechanism=SCRAM-SHA-1' in connection string, and it still can't connect to the server. The error that I get is SASL support not enabled during build (-tags sasl)

thanks,

**Comment by niemeyer** [comment]
The SCRAM-SHA-1 is supported internally, without the need for external SASL support.

Can you please try updating your mgo installation?

Here is a test case, part of the standard suite for v2, ensuring that this actually works:

https://github.com/go-mgo/mgo/blob/v2/auth_test.go#L848

I'm closing this in the belief that you have an out of date driver. If that's not the case, please reopen the issue.
