### ISSUE TITLE
Problem: Arithmetic Aggregation Operators

### ISSUE THREAD

**Issue by pedronasser** [go-mgo/mgo#95]
I'm trying to $project, subtracting two different dates.

MongoDb docs example:
http://docs.mongodb.org/manual/reference/operator/aggregation/subtract/#subtract-milliseconds-from-a-date

In my case, I have to give slice of a `time.Time` and a `string`.
````
bson.M{"$project": bson.M{
	"since":   bson.M{"$subtract": []??????????{time.Now(), "$created"}},
}},
````

There's any way to do that using mgo?

**Comment by niemeyer** [comment]
Yes, anything you can do via the aggregation framework will work with mgo as well. Just build the same document with mgo and run it via the Pipe method:

http://gopkg.in/mgo.v2#Collection.Pipe

**Comment by pedronasser** [comment]
But the problem is: I need to $subtract a time.Time with the attribute "$created" (created inside the aggregation).
I can easily query that using MongoDB client. But how would I reproduce that using Mgo?

**Comment by d6y** [comment]
For anyone else who runs into this, the solution that worked for me was to use the `[]interface{}` style used in [json_test.go](https://github.com/go-mgo/mgo/blob/v2-unstable/bson/json_test.go).

E.g., something like:

```go
bson.M{ "$subtract" : []interface{}{time.Now(), "$created"} }
```

...although I've not tried to compile that, as my use case was slightly different.
